# Community Contribution

This fairly open-ended assignment provides an opportunity to receive credit for contributing to the collective learning of the class, and perhaps beyond. It should reflect a minimum of 3 hours of work. To complete the assignment you must submit a short description of your contribution. If appropriate, attach relevant files.  

There are many ways in which you can contribute:

* organize and lead a workshop on a particular topic (the date may be after the assignment due date but you need to schedule it before)
* help students find final project partners
* give a well-rehearsed 5 minute lightning talk in class on a datavis topic (theory or tool) (email me to set the date -- it may be after the assignment due date but you need to schedule it before)
* create a video tutorial (any length) 
* create a cheatsheet or other resource
* write a tutorial for a tool that's not well documented
* build a viz product (ex. htmlwidget or RStudio add-in) for class use
* [your own idea]
* (Note: translations are not allowed)

You may draw on and expand existing resources.  When doing so, it is critical that you cite your sources.

## IMPORTANT LOGISTICS

### Groups

You may work on your own or with a partner of your choosing. If you work alone, you do not need to join a group of 1, you simply submit your work on CourseWorks as with any other solo assignment. 

If you work with a partner, add yourselves to a group on the CC page on the People tab. Ed Discussion can be used to find partners with similar interests.

### What to submit

1. In most cases you should have something tangible to upload, such as the tutorial, cheatsheet, etc.  Alternatively you may submit a link to material online (YouTube video, etc.) If there's nothing tangible then include a longer description (see 2.).

2. An explanation of the motivation for the project, the need it addresses, and your own evaluation of the project including what you learned / what you might do differently next time. (1/2 page)

### Submitting your assignment

You must submit your assignment twice: once on CourseWorks (so it can be graded) and once to the class, details to follow.

1. CourseWorks submission (this assignment): submit your work as an .Rmd and rendered .pdf or .html file, just as with problem sets. If your work does not lend itself to that format, then write in the assignment text box what you did.

2. Class (GitHub) submission: detail will be provided in a separate assignment.

### Grading

You will be graded on the quality of your work, originality, and the effort invested. Any sources used must be cited.
