# ggplot_matplotlib_cheatsheet

Binghong Yu

For starters, it would be a struggle to learn a new language at first. However, if you happen to have some experience with other programming languages such as python or R, and there is a guide for comparing the two languages who have similar functions side by side, it would be much easier to become familiar with that new language. Thus, I create a cheat sheet for visualization functions and for transformation between most used visualization packages in R (i.e. ggplot) and in python (i.e. Matplotlib).

I spent time searching for documentation about similar plot functions in both languages. Through that process, I become more and more familiar with these plot functions and functions for adjusting scales. In the meantime, through learning these examples, I also learned their differences of the results plotted by different languages and different functions, and their difference in adjusting parameters.

Due to the space restriction, I did not add much details on how to use these functions. Next time, I might add more details about differences between them and parameters we could adjust inside these parentheses.

Click the following link to check out the [cheatsheet](resources/ggplot_Matplotlib_cheatsheet/ggplot_Matplotlib_cheatsheet.pdf)
```

