<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 48 Neural network tools in R | EDAV Fall 2021 Tues/Thurs Community Contributions</title>
<meta name="description" content='Yuan Wang #install.packages("NeuralNetTools") #install.packages("nnet") #install.packages("RSNNS") #install.packages("neuralnet") library("NeuralNetTools") library("RSNNS") library("nnet")...'>
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 48 Neural network tools in R | EDAV Fall 2021 Tues/Thurs Community Contributions">
<meta property="og:type" content="book">
<meta property="og:description" content='Yuan Wang #install.packages("NeuralNetTools") #install.packages("nnet") #install.packages("RSNNS") #install.packages("neuralnet") library("NeuralNetTools") library("RSNNS") library("nnet")...'>
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 48 Neural network tools in R | EDAV Fall 2021 Tues/Thurs Community Contributions">
<meta name="twitter:description" content='Yuan Wang #install.packages("NeuralNetTools") #install.packages("nnet") #install.packages("RSNNS") #install.packages("neuralnet") library("NeuralNetTools") library("RSNNS") library("nnet")...'>
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script><script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script><script src="libs/plotly-binding-4.10.0/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script><link href="libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-2.5.1/plotly-latest.min.js"></script><script src="libs/d3-4.5.0/d3.min.js"></script><script src="libs/forceNetwork-binding-0.4/forceNetwork.js"></script><script src="libs/sankey-1/sankey.js"></script><script src="libs/sankeyNetwork-binding-0.4/sankeyNetwork.js"></script><link href="libs/vis-9.1.0/vis-network.min.css" rel="stylesheet">
<script src="libs/vis-9.1.0/vis-network.min.js"></script><script src="libs/visNetwork-binding-2.1.0/visNetwork.js"></script><link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet">
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script><script src="libs/dygraphs-1.1.1/shapes.js"></script><script src="libs/moment-2.8.4/moment.js"></script><script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script><script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script><script src="libs/dygraphs-binding-1.1.1.6/dygraphs.js"></script><script src="libs/proj4js-2.3.15/proj4.js"></script><link href="libs/highcharts-8.1.2/css/motion.css" rel="stylesheet">
<script src="libs/highcharts-8.1.2/highcharts.js"></script><script src="libs/highcharts-8.1.2/highcharts-3d.js"></script><script src="libs/highcharts-8.1.2/highcharts-more.js"></script><script src="libs/highcharts-8.1.2/modules/stock.js"></script><script src="libs/highcharts-8.1.2/modules/map.js"></script><script src="libs/highcharts-8.1.2/modules/annotations.js"></script><script src="libs/highcharts-8.1.2/modules/data.js"></script><script src="libs/highcharts-8.1.2/modules/drilldown.js"></script><script src="libs/highcharts-8.1.2/modules/item-series.js"></script><script src="libs/highcharts-8.1.2/modules/offline-exporting.js"></script><script src="libs/highcharts-8.1.2/modules/overlapping-datalabels.js"></script><script src="libs/highcharts-8.1.2/modules/exporting.js"></script><script src="libs/highcharts-8.1.2/modules/export-data.js"></script><script src="libs/highcharts-8.1.2/modules/funnel.js"></script><script src="libs/highcharts-8.1.2/modules/heatmap.js"></script><script src="libs/highcharts-8.1.2/modules/treemap.js"></script><script src="libs/highcharts-8.1.2/modules/sankey.js"></script><script src="libs/highcharts-8.1.2/modules/dependency-wheel.js"></script><script src="libs/highcharts-8.1.2/modules/organization.js"></script><script src="libs/highcharts-8.1.2/modules/solid-gauge.js"></script><script src="libs/highcharts-8.1.2/modules/streamgraph.js"></script><script src="libs/highcharts-8.1.2/modules/sunburst.js"></script><script src="libs/highcharts-8.1.2/modules/vector.js"></script><script src="libs/highcharts-8.1.2/modules/wordcloud.js"></script><script src="libs/highcharts-8.1.2/modules/xrange.js"></script><script src="libs/highcharts-8.1.2/modules/tilemap.js"></script><script src="libs/highcharts-8.1.2/modules/venn.js"></script><script src="libs/highcharts-8.1.2/modules/gantt.js"></script><script src="libs/highcharts-8.1.2/modules/timeline.js"></script><script src="libs/highcharts-8.1.2/modules/parallel-coordinates.js"></script><script src="libs/highcharts-8.1.2/modules/bullet.js"></script><script src="libs/highcharts-8.1.2/modules/coloraxis.js"></script><script src="libs/highcharts-8.1.2/modules/dumbbell.js"></script><script src="libs/highcharts-8.1.2/modules/lollipop.js"></script><script src="libs/highcharts-8.1.2/modules/series-label.js"></script><script src="libs/highcharts-8.1.2/plugins/motion.js"></script><script src="libs/highcharts-8.1.2/custom/reset.js"></script><script src="libs/highcharts-8.1.2/modules/boost.js"></script><script src="libs/highchart-binding-0.8.2/highchart.js"></script><script src="libs/detect-resize-0.5.3/jquery.resize.js"></script><link href="libs/jquery-ui-1.11.4/jquery-ui.min.css" rel="stylesheet">
<script src="libs/jquery-ui-1.11.4/jquery-ui.min.js"></script><script src="libs/vega-1.4.3/vega.min.js"></script><script src="libs/lodash-2.2.1/lodash.min.js"></script><script>var lodash = _.noConflict();</script><link href="libs/ggvis-0.4.7/css/ggvis.css" rel="stylesheet">
<script src="libs/ggvis-0.4.7/js/ggvis.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS -->
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">EDAV Fall 2021 Tues/Thurs Community Contributions</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Welcome!</a></li>
<li><a class="" href="community-contribution.html"><span class="header-section-number">2</span> Community Contribution</a></li>
<li><a class="" href="github-submission-instructions.html"><span class="header-section-number">3</span> GitHub submission instructions</a></li>
<li><a class="" href="sample-project.html"><span class="header-section-number">4</span> Sample project</a></li>
<li class="book-part">Cheatsheets</li>
<li><a class="" href="statistics-in-r-vs-python.html"><span class="header-section-number">5</span> Statistics in R vs Python</a></li>
<li><a class="" href="data-visualization-with-seaborn.html"><span class="header-section-number">6</span> Data Visualization with Seaborn</a></li>
<li><a class="" href="how-to-make-your-own-r-package.html"><span class="header-section-number">7</span> How to Make Your Own R package</a></li>
<li><a class="" href="rchess-package-cheatsheet.html"><span class="header-section-number">8</span> RChess package cheatsheet</a></li>
<li><a class="" href="hypothesis-testing-cheatsheet.html"><span class="header-section-number">9</span> Hypothesis testing cheatsheet</a></li>
<li><a class="" href="interactive-web-visualizations-for-r-cheatsheet.html"><span class="header-section-number">10</span> Interactive web visualizations for R cheatsheet"</a></li>
<li><a class="" href="ggforce.html"><span class="header-section-number">11</span> ggforce</a></li>
<li><a class="" href="gganimate-cheatsheet.html"><span class="header-section-number">12</span> GGanimate cheatsheet</a></li>
<li><a class="" href="statistical-tests-and-parameter-estimations-in-r-cheatsheet.html"><span class="header-section-number">13</span> Statistical Tests and Parameter Estimations in R Cheatsheet</a></li>
<li><a class="" href="ggalluvial-cheat-sheet.html"><span class="header-section-number">14</span> ggalluvial-cheat-sheet</a></li>
<li><a class="" href="introduction-to-plotly.html"><span class="header-section-number">15</span> Introduction to plotly</a></li>
<li><a class="" href="draw-graphs-using-python-and-r.html"><span class="header-section-number">16</span> draw graphs using python and R</a></li>
<li><a class="" href="data-visualization-packages-in-r.html"><span class="header-section-number">17</span> Data Visualization Packages in R</a></li>
<li><a class="" href="esquisse-cheat-sheet.html"><span class="header-section-number">18</span> Esquisse Cheat sheet</a></li>
<li><a class="" href="review-sheet-for-r-code-and-data-transformation.html"><span class="header-section-number">19</span> review sheet for r code and data transformation</a></li>
<li><a class="" href="scrape-twitter-data-using-r.html"><span class="header-section-number">20</span> Scrape Twitter data using R</a></li>
<li><a class="" href="r-note-and-mathematics-in-rmd-cheatsheet.html"><span class="header-section-number">21</span> R note and Mathematics in Rmd cheatsheet</a></li>
<li><a class="" href="textbook-notes.html"><span class="header-section-number">22</span> Textbook Notes</a></li>
<li><a class="" href="ggplot2-cheatsheet.html"><span class="header-section-number">23</span> ggplot2 cheatsheet</a></li>
<li><a class="" href="rstudio-cheatsheet.html"><span class="header-section-number">24</span> RStudio Cheatsheet</a></li>
<li><a class="" href="d3-visualization-in-r-cheatsheet.html"><span class="header-section-number">25</span> D3 Visualization in R Cheatsheet</a></li>
<li><a class="" href="colors.html"><span class="header-section-number">26</span> Colors</a></li>
<li><a class="" href="r-data-sets.html"><span class="header-section-number">27</span> R data sets</a></li>
<li><a class="" href="introduction-to-plotly-1.html"><span class="header-section-number">28</span> “Introduction to Plotly”</a></li>
<li><a class="" href="tidyverse-cheatsheet.html"><span class="header-section-number">29</span> Tidyverse Cheatsheet</a></li>
<li class="book-part">Tutorials</li>
<li><a class="" href="tutorial-on-cluster-analysis.html"><span class="header-section-number">30</span> Tutorial on Cluster Analysis</a></li>
<li><a class="" href="how-to-integrate-r-with-postgresql.html"><span class="header-section-number">31</span> How to Integrate R with PostgreSQL</a></li>
<li><a class="" href="apply-function-in-r.html"><span class="header-section-number">32</span> Apply function in r</a></li>
<li><a class="" href="introduction-to-interactive-graphs-in-r.html"><span class="header-section-number">33</span> Introduction to interactive graphs in R</a></li>
<li><a class="" href="plot-and-analyze-stock-data-with-r.html"><span class="header-section-number">34</span> Plot and Analyze Stock Data with R</a></li>
<li><a class="" href="data-visulization-ordering.html"><span class="header-section-number">35</span> Data Visulization Ordering</a></li>
<li><a class="" href="tutorial-on-lattice-package-in-r.html"><span class="header-section-number">36</span> Tutorial on lattice package in R</a></li>
<li><a class="" href="network-visualization-in-r.html"><span class="header-section-number">37</span> Network Visualization in R</a></li>
<li><a class="" href="dplyr-tutorial-in-r.html"><span class="header-section-number">38</span> Dplyr tutorial in R</a></li>
<li><a class="" href="downloading-files.html"><span class="header-section-number">39</span> Downloading files</a></li>
<li><a class="" href="video-introduction-to-maps-with-ggmap.html"><span class="header-section-number">40</span> Video introduction to maps with ggmap</a></li>
<li><a class="" href="comparison-among-base-r-tidyverse-and-datatable.html"><span class="header-section-number">41</span> Comparison among base R, tidyverse, and datatable</a></li>
<li><a class="" href="raincloud-plot-101-density-plot-or-boxplotwhy-not-do-both.html"><span class="header-section-number">42</span> Raincloud plot 101: density plot or boxplot？Why not do both!</a></li>
<li><a class="" href="an-introduction-to-dygraph-in-r.html"><span class="header-section-number">43</span> An Introduction to Dygraph in R</a></li>
<li><a class="" href="streamlit-tutorial.html"><span class="header-section-number">44</span> Streamlit Tutorial</a></li>
<li><a class="" href="hive-plots-with-the-ggraph-and-hiver-packages.html"><span class="header-section-number">45</span> Hive plots with the ggraph and hiver packages</a></li>
<li><a class="" href="introduction-to-xai-explainable-ai-in-r.html"><span class="header-section-number">46</span> Introduction to XAI (Explainable AI) in R</a></li>
<li><a class="" href="tutorial-for-gg_cleveland.html"><span class="header-section-number">47</span> Tutorial for gg_cleveland</a></li>
<li><a class="active" href="neural-network-tools-in-r.html"><span class="header-section-number">48</span> Neural network tools in R</a></li>
<li><a class="" href="r-dplyr-vs-python-pandas.html"><span class="header-section-number">49</span> R Dplyr vs Python Pandas</a></li>
<li><a class="" href="readable-plots.html"><span class="header-section-number">50</span> Readable Plots</a></li>
<li><a class="" href="introduction-to-exploratory-spatial-data-analysis-and-visualization-using-qgis.html"><span class="header-section-number">51</span> Introduction to exploratory spatial data analysis and visualization using QGIS</a></li>
<li><a class="" href="data-visualization-in-python-vs-r.html"><span class="header-section-number">52</span> Data Visualization in Python vs R</a></li>
<li><a class="" href="base-r-tutorial.html"><span class="header-section-number">53</span> Base R Tutorial</a></li>
<li><a class="" href="python-altair-visualization-method-tutorial.html"><span class="header-section-number">54</span> Python Altair Visualization Method Tutorial</a></li>
<li><a class="" href="r-to-python-easy-plot.html"><span class="header-section-number">55</span> R to python easy plot</a></li>
<li><a class="" href="introduction-to-models-and-prediction-evaluation.html"><span class="header-section-number">56</span> Introduction to models and prediction evaluation</a></li>
<li><a class="" href="introduction-to-interactive-time-series-visualizations-with-dygraphs-in-r.html"><span class="header-section-number">57</span> Introduction to Interactive Time Series Visualizations with dygraphs in R</a></li>
<li><a class="" href="integrate-r-with-python.html"><span class="header-section-number">58</span> Integrate R with Python</a></li>
<li><a class="" href="python-visualization-tutorial.html"><span class="header-section-number">59</span> Python Visualization Tutorial</a></li>
<li><a class="" href="gganimate-tutorial.html"><span class="header-section-number">60</span> Gganimate Tutorial</a></li>
<li><a class="" href="get-nba-dataset-in-r.html"><span class="header-section-number">61</span> Get NBA dataset in R</a></li>
<li><a class="" href="mtemplates.html"><span class="header-section-number">62</span> Mtemplates</a></li>
<li><a class="" href="introduction-to-time-series-analysis-in-r.html"><span class="header-section-number">63</span> Introduction to Time Series Analysis in R</a></li>
<li><a class="" href="storytelling-with-data.html"><span class="header-section-number">64</span> Storytelling with Data</a></li>
<li><a class="" href="tutorial-on-r-torch-package.html"><span class="header-section-number">65</span> Tutorial on R torch package</a></li>
<li><a class="" href="edav-tutorials-correlogram-calendar-heatmap-and-slopegram.html"><span class="header-section-number">66</span> EDAV Tutorials: Correlogram, Calendar Heatmap and Slopegram</a></li>
<li><a class="" href="recursive-codes-and-self-organized-map-with-r.html"><span class="header-section-number">67</span> Recursive codes and self-organized map with R</a></li>
<li><a class="" href="tutorial-of-three-ggplot2-based-packages.html"><span class="header-section-number">68</span> Tutorial of three ggplot2 based packages</a></li>
<li><a class="" href="a-step-by-step-tutorial-for-natural-language-processing-in-r.html"><span class="header-section-number">69</span> A Step by Step Tutorial for Natural Language Processing in R</a></li>
<li><a class="" href="tutorial-for-ggvis-and-its-comparison-with-ggplot2.html"><span class="header-section-number">70</span> Tutorial for ggvis and its Comparison with ggplot2</a></li>
<li><a class="" href="feature-selection-in-r.html"><span class="header-section-number">71</span> Feature selection in r</a></li>
<li><a class="" href="debugging-in-rstudio.html"><span class="header-section-number">72</span> Debugging in Rstudio</a></li>
<li><a class="" href="r-tutorial-cheatsheet.html"><span class="header-section-number">73</span> R tutorial cheatsheet</a></li>
<li><a class="" href="brief-introduction-of-ggpubr.html"><span class="header-section-number">74</span> Brief Introduction of ggpubr</a></li>
<li><a class="" href="r-based-data-organization-and-visualization.html"><span class="header-section-number">75</span> R based data organization and visualization</a></li>
<li><a class="" href="r-packages-for-map-visualization.html"><span class="header-section-number">76</span> R packages for map Visualization</a></li>
<li><a class="" href="common-git-command-lines-tutorial-when-working-on-studio.html"><span class="header-section-number">77</span> Common git command lines tutorial when working on studio</a></li>
<li><a class="" href="tutorial-of-radar-chart.html"><span class="header-section-number">78</span> Tutorial of radar chart</a></li>
<li><a class="" href="interactive-radar.html"><span class="header-section-number">79</span> Interactive Radar</a></li>
<li><a class="" href="r-shiny-tutorial.html"><span class="header-section-number">80</span> R shiny tutorial</a></li>
<li><a class="" href="tutorial-on-r-markdown.html"><span class="header-section-number">81</span> Tutorial on R Markdown</a></li>
<li class="book-part">Project &amp; Workshops</li>
<li><a class="" href="introduction-to-analytics-consulting-at-accenture.html"><span class="header-section-number">82</span> Introduction to analytics consulting at Accenture</a></li>
<li><a class="" href="map-of-the-r-world.html"><span class="header-section-number">83</span> Map of the R world</a></li>
<li><a class="" href="alluvial-diagrams-and-their-implementation-using-ggalluvial-in-r.html"><span class="header-section-number">84</span> Alluvial diagrams and their implementation using GGalluvial in R</a></li>
<li><a class="" href="building-a-dashboard-in-r-for-data-analysis-and-visualization-using-shiny-package.html"><span class="header-section-number">85</span> Building a Dashboard in R for Data Analysis and Visualization using shiny package</a></li>
<li><a class="" href="rgl-package.html"><span class="header-section-number">86</span> RGL Package</a></li>
<li class="book-part">Data Visualization</li>
<li><a class="" href="an-introduction-to-pyecharts-package-in-python.html"><span class="header-section-number">87</span> An introduction to pyecharts package in Python</a></li>
<li><a class="" href="visualization-in-r-v.s.-python.html"><span class="header-section-number">88</span> Visualization in R v.s. Python</a></li>
<li><a class="" href="understand-data-with-plots.html"><span class="header-section-number">89</span> Understand data with plots</a></li>
<li><a class="" href="r-and-python-visualization.html"><span class="header-section-number">90</span> R and Python visualization</a></li>
<li><a class="" href="super-ggformat.html"><span class="header-section-number">91</span> Super ggformat</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="github-initial-setup.html"><span class="header-section-number">92</span> Github initial setup</a></li>
<li><a class="" href="tutorial-for-pull-request-mergers.html"><span class="header-section-number">93</span> Tutorial for pull request mergers</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/jtr13/cc21fall2">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="neural-network-tools-in-r" class="section level1">
<h1>
<span class="header-section-number">48</span> Neural network tools in R<a class="anchor" aria-label="anchor" href="#neural-network-tools-in-r"><i class="fas fa-link"></i></a>
</h1>
<p>Yuan Wang</p>
<div class="sourceCode" id="cb614"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#install.packages("NeuralNetTools")</span>
<span class="co">#install.packages("nnet")</span>
<span class="co">#install.packages("RSNNS")</span>
<span class="co">#install.packages("neuralnet")</span>

<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st">"NeuralNetTools"</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/cbergmeir/RSNNS">"RSNNS"</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="http://www.stats.ox.ac.uk/pub/MASS4/">"nnet"</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/bips-hb/neuralnet">"neuralnet"</a></span><span class="op">)</span></code></pre></div>
<div id="introduction-9" class="section level2">
<h2>
<span class="header-section-number">48.1</span> Introduction<a class="anchor" aria-label="anchor" href="#introduction-9"><i class="fas fa-link"></i></a>
</h2>
<p>Deep learning plays a key role in today’s data science, given the advance of accessible computing resources and the algorithm’s performance and versatility. However, building an efficient neural network requires careful architecture
design which is crucial for improving the output accuracy of the network’s
prediction. Since neural network is designed to train extremely large
datasets, it’s often difficult to come up with ideas of fine tuning the
model. Thus, providing a visual representation allows us to inspect its
structure more clearly. With the help of R packages NeuralNetTools, we
can visualize the network’s structure, evaluate variable importance and
conduct sensitivity analysis, which makes it easier to interpret and
gives insights into fine-tuning strategies.</p>
<div id="packages-will-be-introduced" class="section level3">
<h3>
<span class="header-section-number">48.1.1</span> Packages will be introduced:<a class="anchor" aria-label="anchor" href="#packages-will-be-introduced"><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: decimal">
<li>Basics: Neuralnettools, nnet, Neuralnet, RSNNS,</li>
<li>Additional: keras</li>
</ol>
</div>
<div id="some-background-knowledge-of-neural-networks" class="section level3">
<h3>
<span class="header-section-number">48.1.2</span> Some background knowledge of neural networks:<a class="anchor" aria-label="anchor" href="#some-background-knowledge-of-neural-networks"><i class="fas fa-link"></i></a>
</h3>
<p>This tutorial focuses on supervised learning problems where the goal of
the neural network is to map inputs to given labels. In a supervised
learning setting, the datasets will contain: 1. Observations: - data
collected to be trained and tested</p>
<ol start="2" style="list-style-type: decimal">
<li><p>Inputs: random observations from a standard normal distribution</p></li>
<li><p>Input variables (X’s in regression): features that may represent the
labels</p></li>
<li><p>Outputs (Y’s in regression): predictions of targeted labels using
linear combinations of the input variables with additional random
components (they are scaled from 0 to 1 using softmax function)</p></li>
</ol>
</div>
<div id="data-pre-processing" class="section level3">
<h3>
<span class="header-section-number">48.1.3</span> Data pre-processing<a class="anchor" aria-label="anchor" href="#data-pre-processing"><i class="fas fa-link"></i></a>
</h3>
<div id="common-approach-for-deep-learning" class="section level4">
<h4>
<span class="header-section-number">48.1.3.1</span> Common approach for deep learning:<a class="anchor" aria-label="anchor" href="#common-approach-for-deep-learning"><i class="fas fa-link"></i></a>
</h4>
<ol style="list-style-type: decimal">
<li><p>Normalize the input variables (inputs —&gt; X’s)</p></li>
<li><p>Standardize the response variables (predictions/fitted values —&gt;
Y’s)</p></li>
<li><p>For images, it also need to be flattened to new shape.</p></li>
</ol>
<p>The purpose of pre-processing data is to standardize the data to make
them range from 0 to 1. To demonstrate this approach, we use MNIST
dataset which consists of 28 x 28 grayscale images of handwritten
digits.</p>
<p>Loading well-known neural net dataset such as MNIST requires package keras which is R’s interface to
Keras, a widely used high-level neural networks API built in python. Note that R’s
miniconda is also required and TensorFlow should be installed by “install_tensorflow()” to prevent loading errors. Datasets for neural networks in keras are already standardized, but we still need to do an extra step of reshaping them.</p>
</div>
<div id="reshape" class="section level4">
<h4>
<span class="header-section-number">48.1.3.2</span> Reshape<a class="anchor" aria-label="anchor" href="#reshape"><i class="fas fa-link"></i></a>
</h4>
<p>Neural networks are heavily used in computer vision where datasets are
images that were 3-dimensional array (images,width,height) of grayscale
values. So first we need to flatten the 3-d array into a matrix by
reshaping it into a single dimension. In MNIST images are 28x28 array
which will be flatten to a vector of length 784. To do so, we use keras
function array_reshape(data, newshape). The “data” parameter should be
array-like and the “newshape” parameter should be an integer or array.
If it’s an integer, say n, “data” will be shaped to a matrix of n rows
with #columns = size(data)/n. If it’s an array, it should be compatible
with the original 3-d array, so size(newshape) = size(data). Keras provides the array_shape() function to do reshaping. For MNIST data, reshaping can be accomplished by “array_reshape(x_train, c(nrow(x_train), 784))”.</p>
<p>The goal of the neural network is to correctly identify the written
digit in the image. Since this tutorial focuses on visualization, you
can find more information and the code to train MNIST using keras in
<a href="https://rdrr.io/cran/keras/f/vignettes/index.Rmd" class="uri">https://rdrr.io/cran/keras/f/vignettes/index.Rmd</a>.</p>
</div>
</div>
</div>
<div id="visualization-of-neural-networks" class="section level2">
<h2>
<span class="header-section-number">48.2</span> Visualization of Neural Networks<a class="anchor" aria-label="anchor" href="#visualization-of-neural-networks"><i class="fas fa-link"></i></a>
</h2>
<div id="neuralnettools-package" class="section level3">
<h3>
<span class="header-section-number">48.2.1</span> Neuralnettools package<a class="anchor" aria-label="anchor" href="#neuralnettools-package"><i class="fas fa-link"></i></a>
</h3>
<p>A set of visualization and analysis tools used to interpret the
structure of neural net models. This is the main package for plotting a
neural interpretation diagram (NID) with nodes, layers and edges, to
help you visually understand its architecture and training progress. The
visualization can give you some insights into how to fine tune the
model.</p>
</div>
<div id="four-core-functions-of-neuralnettools" class="section level3">
<h3>
<span class="header-section-number">48.2.2</span> Four core functions of NeuralNetTools<a class="anchor" aria-label="anchor" href="#four-core-functions-of-neuralnettools"><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: decimal">
<li><p>plotnet: to plot the for visualization</p></li>
<li><p>garson &amp; olden: to evaluate importance of input variables</p></li>
<li><p>lekprofile: to conduct sensitivity analysis (how sensitive is an
input variable?)</p></li>
</ol>
<p>These functions are built upon nnet, neuralnet, RSNNS, and caret.</p>
</div>
<div id="neural-interpretation-diagram-nid" class="section level3">
<h3>
<span class="header-section-number">48.2.3</span> Neural Interpretation Diagram (NID)<a class="anchor" aria-label="anchor" href="#neural-interpretation-diagram-nid"><i class="fas fa-link"></i></a>
</h3>
<p>Neural interpretatiion diagram (NID) is a graph representation with
nodes and edges divided into vertical layers. The stages of training the
network can be seen horizontally. Nodes represent three types of
variables of the underlying neural network 1. Input variables (1st
layer) 2. Hidden variables (layers between 1st and last layers) 3.
Output variables (last layer)</p>
<p>The nodes are called units in neural networks. The connection between a
pair of nodes is like a directed edge from the node in the former layer
to the pointed node in the next layer. It represent the existence of
contribution from the predecessor node to the next node. For example, if
there is a connection from node x to node y, x is included in the linear
combination of y.</p>
<p>The diagram illustrates the idea of a feedforward neural network where
information only moves in one direction which is the horizontal
direction of the NID. It’s best illustrated with an actual NID.</p>
<p>Load the data and train the dataset using three different
functions.</p>
<p>A simple dataset from neuraldat is used for the purpose of
demonstration. Summaries of training results are assigned to “mod#”
variable which will be used as arguments for visualization later.</p>
<p>Example: neuraldat (normalized dataset in NerualNetTools). It contains -
2000 rows of observations - 3 input variables (X1, X2, and X3) - 5
columns of two response variables (Y1 and Y2)</p>
<p>(Note: if package loading Rcpp error occurs, try update.packages() to
update packages in your r environment)</p>
<div class="sourceCode" id="cb615"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span>

<span class="va">x</span> <span class="op">&lt;-</span> <span class="va">neuraldat</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"X1"</span>, <span class="st">"X2"</span>, <span class="st">"X3"</span><span class="op">)</span><span class="op">]</span>
<span class="va">y</span> <span class="op">&lt;-</span> <span class="va">neuraldat</span><span class="op">[</span>, <span class="st">"Y1"</span><span class="op">]</span>

<span class="va">mod1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/RSNNS/man/mlp.html">mlp</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, size <span class="op">=</span> <span class="fl">5</span><span class="op">)</span>

<span class="va">mod2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/neuralnet/man/neuralnet.html">neuralnet</a></span><span class="op">(</span><span class="va">Y1</span> <span class="op">~</span> <span class="va">X1</span> <span class="op">+</span> <span class="va">X2</span> <span class="op">+</span> <span class="va">X3</span>, data <span class="op">=</span> <span class="va">neuraldat</span>, hidden <span class="op">=</span> <span class="fl">5</span><span class="op">)</span>

<span class="va">mod3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nnet/man/nnet.html">nnet</a></span><span class="op">(</span><span class="va">Y1</span> <span class="op">~</span> <span class="va">X1</span> <span class="op">+</span> <span class="va">X2</span> <span class="op">+</span> <span class="va">X3</span>, data <span class="op">=</span> <span class="va">neuraldat</span>, size <span class="op">=</span> <span class="fl">5</span><span class="op">)</span></code></pre></div>
<pre><code>## # weights:  26
## initial  value 102.608189 
## iter  10 value 0.420687
## iter  20 value 0.230286
## iter  30 value 0.161667
## iter  40 value 0.042549
## iter  50 value 0.019999
## iter  60 value 0.016232
## iter  70 value 0.013683
## iter  80 value 0.011934
## iter  90 value 0.011545
## iter 100 value 0.010132
## final  value 0.010132 
## stopped after 100 iterations</code></pre>
<p>We can then plot NIDs of the models above using plotnet:</p>
<div class="sourceCode" id="cb617"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/plotnet.html">plotnet</a></span><span class="op">(</span><span class="va">mod1</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-4-1.png" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb618"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/plotnet.html">plotnet</a></span><span class="op">(</span><span class="va">mod2</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-4-2.png" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb619"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/plotnet.html">plotnet</a></span><span class="op">(</span><span class="va">mod3</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-4-3.png" width="672" style="display: block; margin: auto;"></div>
<p>Notice that if you run the models several time, each run will give you a
different result and thus a different NID plot. The difference is in the
direction, color and thickness of the connections which will discussed
in details later.</p>
<div id="when-to-terminate-the-training" class="section level4">
<h4>
<span class="header-section-number">48.2.3.1</span> When to terminate the training<a class="anchor" aria-label="anchor" href="#when-to-terminate-the-training"><i class="fas fa-link"></i></a>
</h4>
<p>Running nnet() will output a list of the loss of each tenth iteration up
to 100. You can see here the traning stops at an error of 0.010132
between the target (ground truth) and the fitted value. It does not
satisfy the default absolute tolerance of the fitting criterion, but
training reaches the default maximum number of iterations of 100 so that
it stops.</p>
<p>In other words, the training process will stop under two conditions:</p>
<p>1. its loss is smaller than the fitting criterion, or</p>
<p>2. it reaches the maximum number of iterations allowed.</p>
<p>We can customize the two by specifying tolerance and maxit in nnet().</p>
<div class="sourceCode" id="cb620"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nnet/man/nnet.html">nnet</a></span><span class="op">(</span><span class="va">Y1</span> <span class="op">~</span> <span class="va">X1</span> <span class="op">+</span> <span class="va">X2</span> <span class="op">+</span> <span class="va">X3</span>, data <span class="op">=</span> <span class="va">neuraldat</span>, size <span class="op">=</span> <span class="fl">5</span>, maxit<span class="op">=</span><span class="fl">200</span><span class="op">)</span></code></pre></div>
<pre><code>## # weights:  26
## initial  value 74.693524 
## iter  10 value 0.458543
## iter  20 value 0.180504
## iter  30 value 0.030452
## iter  40 value 0.025113
## iter  50 value 0.021237
## iter  60 value 0.017340
## iter  70 value 0.009561
## iter  80 value 0.005930
## iter  90 value 0.005084
## iter 100 value 0.004484
## iter 110 value 0.004201
## iter 120 value 0.004032
## iter 130 value 0.003599
## iter 140 value 0.002484
## iter 150 value 0.002059
## iter 160 value 0.002014
## iter 170 value 0.002009
## iter 180 value 0.001882
## iter 190 value 0.001719
## iter 200 value 0.001654
## final  value 0.001654 
## stopped after 200 iterations</code></pre>
<div class="sourceCode" id="cb622"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod5</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nnet/man/nnet.html">nnet</a></span><span class="op">(</span><span class="va">Y1</span> <span class="op">~</span> <span class="va">X1</span> <span class="op">+</span> <span class="va">X2</span> <span class="op">+</span> <span class="va">X3</span>, data <span class="op">=</span> <span class="va">neuraldat</span>, size <span class="op">=</span> <span class="fl">5</span>, maxit<span class="op">=</span><span class="fl">300</span>, abstol<span class="op">=</span><span class="fl">0.01</span><span class="op">)</span></code></pre></div>
<pre><code>## # weights:  26
## initial  value 95.238709 
## iter  10 value 0.639464
## iter  20 value 0.111136
## iter  30 value 0.034965
## iter  40 value 0.027499
## iter  50 value 0.022252
## iter  60 value 0.017605
## iter  70 value 0.014490
## iter  80 value 0.011656
## final  value 0.009720 
## converged</code></pre>
<p>Clearly we see from the outputs that mod4 runs 200 iterations and
stopped at a loss of 0.002367 which does not reach the fitting
criterion, while mod5, which specifies an absolute tolerance of 0.01 and
a maximum of 300 iterations, converges with a final loss value of
0.009917 and terminates after 110 iterations (did not use up all 300
iterations because the fitting criterion is satisfied).</p>
</div>
<div id="further-explaination-of-the-three-model-functions-used-above" class="section level4">
<h4>
<span class="header-section-number">48.2.3.2</span> Further explaination of the three model functions used above:<a class="anchor" aria-label="anchor" href="#further-explaination-of-the-three-model-functions-used-above"><i class="fas fa-link"></i></a>
</h4>
<ol style="list-style-type: decimal">
<li>“mlp”:</li>
</ol>
<ul>
<li><p>A multilayer perceptron (MLP), which is fully connected feedforward
networks (probably most common network architecture in practice)</p></li>
<li>
<p>Some useful options:</p>
<ul>
<li><p>hiddenActFunc: the activation function of all hidden units
(popular choice: ReLU)</p></li>
<li><p>outputActFunc: the activation function of all output units
(popular choice: softmax)</p></li>
<li><p>inputsTest: a matrix of the testing set to examine the fitting
of the model</p></li>
<li><p>pruneFunc &amp; pruneFunParams: pruning function and parameters
(explained later)</p></li>
<li>
<p>size: specifies the number of units in hidden layers.</p>
<ul>
<li>When using multiple hidden layers, specify the size argument
to be a vector whose length equals the number of layers and
i-th element of this vector is the number of units in i-th
hidden layer.</li>
<li>ex. mlp(x, y, size = c(5, 6)) –&gt; two hidden layers and the
1st layer has 5 units and the 2nd layer has 6 units.</li>
</ul>
<div class="sourceCode" id="cb624"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod6</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/RSNNS/man/mlp.html">mlp</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, size <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">6</span><span class="op">)</span><span class="op">)</span>
<span class="co"># visualize the model using plotnet</span>
<span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/plotnet.html">plotnet</a></span><span class="op">(</span><span class="va">mod6</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-6-1.png" width="672" style="display: block; margin: auto;"></div>
</li>
</ul>
</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>“neuralnet”:</li>
</ol>
<ul>
<li>It also supports multi-layer networks by specifying “hidden”
argument (just like the “size” argument in mlp)</li>
<li>It is flexible in terms of setting loss and activation function</li>
<li>But it only provide minimal visual interpretation of the network
with the basic structure which mainly illustrates connections
between layers</li>
</ul>
<p>Using neuralnet for multilayer:</p>
<p>Ex. three hidden layers with 3 units, 5 units and 7 units respectively.</p>
<div class="sourceCode" id="cb625"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod7</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/neuralnet/man/neuralnet.html">neuralnet</a></span><span class="op">(</span><span class="va">Y1</span> <span class="op">~</span> <span class="va">X1</span> <span class="op">+</span> <span class="va">X2</span> <span class="op">+</span> <span class="va">X3</span>, data <span class="op">=</span> <span class="va">neuraldat</span>, hidden <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">5</span>, <span class="fl">7</span><span class="op">)</span><span class="op">)</span>
<span class="co"># visualize the model using plotnet</span>
<span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/plotnet.html">plotnet</a></span><span class="op">(</span><span class="va">mod7</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-7-1.png" width="672" style="display: block; margin: auto;"></div>
<ol start="3" style="list-style-type: decimal">
<li>“nnet(x, …)”</li>
</ol>
<ul>
<li><p>Provides customization for visualization to demonstrate variable
importance reflected by the units and edges</p></li>
<li><p>But it only supports feedforward neural networks with single hidden
layer</p></li>
<li>
<p>Syntax:</p>
<p>nnet(formula, data, weights, …, subset, na.action, contrasts =
NULL)</p>
<p>nnet(x, y, weights, size, Wts, mask, linout = FALSE, entropy =
FALSE, softmax = FALSE, censored = FALSE, skip = FALSE, rang = 0.7,
decay = 0, maxit = 100, Hess = FALSE, trace = TRUE, MaxNWts = 1000,
abstol = 1.0e-4, reltol = 1.0e-8, …)</p>
</li>
<li><p>Some useful nnet options:</p></li>
</ul>
<div class="inline-table"><table style="width:99%;" class="table table-sm">
<colgroup>
<col width="15%">
<col width="83%">
</colgroup>
<thead><tr class="header">
<th>name</th>
<th>description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>formula</td>
<td>linear combination of x’s for y</td>
</tr>
<tr class="even">
<td>x</td>
<td>matrix or data frame of input variables X</td>
</tr>
<tr class="odd">
<td>y</td>
<td>matrix or data frame of Y</td>
</tr>
<tr class="even">
<td>weights</td>
<td>(case) weights for each example (default: 1)</td>
</tr>
<tr class="odd">
<td>size</td>
<td>number of units in the hidden layers</td>
</tr>
<tr class="even">
<td>subset</td>
<td>an index vector containing which observations will be
used in training. The rest is for the test set.</td>
</tr>
<tr class="odd">
<td>Wts</td>
<td>initialization of weights - it will get more accurate as
the training progresses; default: randomly chosen.</td>
</tr>
<tr class="even">
<td>entropy</td>
<td>switch for maximum conditional likelihood likelihood
(default to least-square)</td>
</tr>
<tr class="odd">
<td>softmax</td>
<td>switch for softmax and maximum conditional likelihood
likelihood (default to least-square)</td>
</tr>
<tr class="even">
<td>skip</td>
<td>add skip-layer connections from input to output to the
primary netwrork - viewing both primary and skip networks
is recommemded to see which one has larger relative
weights - in the case of no hidden layers, plotting a
network with only a skip layer will include bias
connections to the output layer</td>
</tr>
<tr class="odd">
<td>decay</td>
<td>parameter for weight decay - weight decay is used to
penalize complexity of haveing too many units by adding
the weights to the loss function</td>
</tr>
<tr class="even">
<td>maxit</td>
<td>maximum number of iterations MaxNwts: maximum allowable
number of weights</td>
</tr>
<tr class="odd">
<td>abstol</td>
<td>stopping criterion of the training (absolute tolerance) -
Example: default value is abstol = 1.0e-4, so if the
absolute error between ground truth and the model’s
prediction falls below 1.0e-4, the training ends.</td>
</tr>
<tr class="even">
<td>reltol</td>
<td>stopping criterion relative to the previous errors
(relative tolerance) - Example: default value is reltol =
1.0e-8, so if the relative error between ground truth and
the model’s prediction falls below 1.0e-8, the training
ends.</td>
</tr>
</tbody>
</table></div>
<p>Note that the differe between “abstol” and “reltol” is that
Abs(prediction - target) &lt;= absTol, OR Abs(preiction - target) &lt;=
relTol * Max(Abs(prediction), Abs(target))</p>
</div>
</div>
<div id="neuralnettoolsplotnet" class="section level3">
<h3>
<span class="header-section-number">48.2.4</span> NeuralNetTools::plotnet<a class="anchor" aria-label="anchor" href="#neuralnettoolsplotnet"><i class="fas fa-link"></i></a>
</h3>
<p>This is the plotting function to visualize the neural networks from the
model. It will plot a diagram of net structure (NID), with support of
customization. Features of a NID includes:</p>
<div class="inline-table"><table style="width:99%;" class="table table-sm">
<colgroup>
<col width="29%">
<col width="69%">
</colgroup>
<thead><tr class="header">
<th>Feature</th>
<th>Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Connection is a
black line</td>
<td>Black means it’s a positive weight</td>
</tr>
<tr class="even">
<td>Connection is a
gray line</td>
<td>Gray means it’s a negative weight</td>
</tr>
<tr class="odd">
<td>Line thickness</td>
<td>Visually show the magnitude of the node’s
weight (thicker lines mean larger weights, so
the node is more influential)</td>
</tr>
</tbody>
</table></div>
<ul>
<li>
<p>Examples of plotnet’s more advanced customization:</p>
<ol style="list-style-type: decimal">
<li>
<p>Primary and skip layer network:</p>
<ul>
<li>skip bypasses hidden layers, to demonstrate logical
connections from the input layer to the output layer</li>
</ul>
</li>
<li>
<p>Prune connections or nodes (RSNNS package):</p>
<ul>
<li>The idea of pruning is to remove connections or nodes in the
network, if they do not contribute to the netwaork’s
performance of predicting targets (hteir weights are close
to zero). Doing so improves the network’s performance, since
it reduces the number of estimations of wieghts.</li>
</ul>
</li>
</ol>
</li>
</ul>
<p>Code:</p>
<div class="sourceCode" id="cb626"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># skip</span>
<span class="va">mod1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nnet/man/nnet.html">nnet</a></span><span class="op">(</span><span class="va">Y1</span> <span class="op">~</span> <span class="va">X1</span> <span class="op">+</span> <span class="va">X2</span> <span class="op">+</span> <span class="va">X3</span>, data <span class="op">=</span> <span class="va">neuraldat</span>, size <span class="op">=</span> <span class="fl">5</span><span class="op">)</span></code></pre></div>
<pre><code>## # weights:  26
## initial  value 37.536429 
## iter  10 value 3.473930
## iter  20 value 0.300459
## iter  30 value 0.110746
## iter  40 value 0.075740
## iter  50 value 0.029781
## iter  60 value 0.021122
## iter  70 value 0.012062
## iter  80 value 0.011070
## iter  90 value 0.009380
## iter 100 value 0.006579
## final  value 0.006579 
## stopped after 100 iterations</code></pre>
<div class="sourceCode" id="cb628"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/plotnet.html">plotnet</a></span><span class="op">(</span><span class="va">mod1</span>, skip <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> </code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-8-1.png" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb629"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># prune</span>
<span class="co"># pruned model using code from RSSNS pruning demo</span>
<span class="va">pruneFuncParams</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>max_pr_error_increase <span class="op">=</span> <span class="fl">10.0</span>,
                        pr_accepted_error <span class="op">=</span> <span class="fl">1.0</span>,
                        no_of_pr_retrain_cycles <span class="op">=</span> <span class="fl">1000</span>,
                        min_error_to_stop <span class="op">=</span> <span class="fl">0.01</span>, 
                        init_matrix_value <span class="op">=</span> <span class="fl">1e-6</span>,
                        input_pruning <span class="op">=</span> <span class="cn">TRUE</span>, 
                        hidden_pruning <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>

<span class="va">mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/RSNNS/man/mlp.html">mlp</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, size <span class="op">=</span> <span class="fl">5</span>, pruneFunc <span class="op">=</span> <span class="st">"OptimalBrainSurgeon"</span>,
           pruneFuncParams <span class="op">=</span> <span class="va">pruneFuncParams</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/plotnet.html">plotnet</a></span><span class="op">(</span><span class="va">mod</span>, rel_rsc <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">8</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-8-2.png" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb630"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/plotnet.html">plotnet</a></span><span class="op">(</span><span class="va">mod</span>, prune_col <span class="op">=</span> <span class="st">"lightblue"</span>, rel_rsc <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">8</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-8-3.png" width="672" style="display: block; margin: auto;"></div>
<p>RSNNSs provides several prune functions, including MagPruning,
OptimalBrainSurgeon, OptimalBrainDamage, Noncontributing_Units, and
Skeletonization. You can review the original OBS paper here
<a href="https://authors.library.caltech.edu/54981/1/Optimal%20Brain%20Surgeon%20and%20general%20network%20pruning.pdf" class="uri">https://authors.library.caltech.edu/54981/1/Optimal%20Brain%20Surgeon%20and%20general%20network%20pruning.pdf</a>,
which can give you more perspectives into pruning.</p>
<p>The pruneFuncParames are arguments we pass to the prune function. For
example, in the code above, the parameters it uses are:</p>
<div class="inline-table"><table style="width:99%;" class="table table-sm">
<colgroup>
<col width="26%">
<col width="72%">
</colgroup>
<thead><tr class="header">
<th>Parameter</th>
<th>Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>max_p
r_error_increase</td>
<td>Maximum error increase in % (float)</td>
</tr>
<tr class="even">
<td>p
r_accepted_error</td>
<td>Accepted error (float)</td>
</tr>
<tr class="odd">
<td>no_of_p
r_retrain_cycles</td>
<td>Number of cycles for retraining (integer)</td>
</tr>
<tr class="even">
<td>m
in_error_to_stop</td>
<td>Minimum error to stop (float)</td>
</tr>
<tr class="odd">
<td>i
nit_matrix_value</td>
<td>Initial value for matrix (float)</td>
</tr>
<tr class="even">
<td>input_pruning</td>
<td>if true, do input pruning (boolean)</td>
</tr>
<tr class="odd">
<td>hidden_pruning</td>
<td>if true, do hidden pruning (boolean)</td>
</tr>
</tbody>
</table></div>
</div>
<div id="alternative-to-nid" class="section level3">
<h3>
<span class="header-section-number">48.2.5</span> Alternative to NID:<a class="anchor" aria-label="anchor" href="#alternative-to-nid"><i class="fas fa-link"></i></a>
</h3>
<p>The neural network is often complex with large numbers of layers, nodes,
and edges, which makes it difficult to interpret. In this case, we can
use the second and third main functions of the packages, garson and
olden as alternatives by deconstructing the weights to interpret
variable importance.</p>
<p>They are named after two approaches:</p>
<ol style="list-style-type: decimal">
<li>
<p>Garson’s</p>
<p>It analyzes relative importance of each variable through magnitude.</p>
<ul>
<li>
<p>Limitation:</p>
<ul>
<li><p>Sometimes responses cannot be determined</p></li>
<li><p>It can only evaluate neural nets with one hidden and one
output node</p></li>
</ul>
</li>
</ul>
</li>
<li>
<p>Olden’s</p>
<p>A more flexible approach by measuring variable importance as the
summed product of input-hidden and hidden-output onnection weights
between input and output</p>
<ul>
<li>
<p>Advantages:</p>
<ul>
<li>maintain both magnitude and sign. Thus, the canceling effect
resulted from different signs of incoming and out coming
connections of an node is maintained.</li>
<li>It can evaluate multiple hidden layers and responses.</li>
</ul>
</li>
</ul>
</li>
</ol>
<div class="sourceCode" id="cb631"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/garson.html">garson</a></span><span class="op">(</span><span class="va">mod1</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-9-1.png" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb632"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/garson.html">garson</a></span><span class="op">(</span><span class="va">mod2</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-9-2.png" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb633"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/garson.html">garson</a></span><span class="op">(</span><span class="va">mod5</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-9-3.png" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb634"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/olden.html">olden</a></span><span class="op">(</span><span class="va">mod1</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-9-4.png" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb635"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/olden.html">olden</a></span><span class="op">(</span><span class="va">mod2</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-9-5.png" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb636"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/olden.html">olden</a></span><span class="op">(</span><span class="va">mod5</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-9-6.png" width="672" style="display: block; margin: auto;"></div>
<p>These bar chars of the importance of each input variable provides a
straightforward visual presentation of <strong>how influential each variable
is to the outputs.</strong></p>
</div>
<div id="sensitivity-analysis" class="section level3">
<h3>
<span class="header-section-number">48.2.6</span> Sensitivity analysis:<a class="anchor" aria-label="anchor" href="#sensitivity-analysis"><i class="fas fa-link"></i></a>
</h3>
<p>Sensitivity analysis shows how sensitive an input variable (feature) and
is necessary for us to <strong>understand the relationship and the influence
of each input parameter on the outputs.</strong></p>
<div id="lekprofile" class="section level4">
<h4>
<span class="header-section-number">48.2.6.1</span> Lekprofile<a class="anchor" aria-label="anchor" href="#lekprofile"><i class="fas fa-link"></i></a>
</h4>
<p>This function uses Lek’s profile method to evaluate the behavior of
outputs across different values of the input variables. It’s generic and
can be applied to any predictive method.</p>
<p>Two options for setting constant values of unevaluated explanatory
variables:</p>
<div class="inline-table"><table style="width:99%;" class="table table-sm">
<colgroup>
<col width="19%">
<col width="79%">
</colgroup>
<thead><tr class="header">
<th>Parameter</th>
<th>Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>group_vals</td>
<td>
<p>A vector with calues from 0-1 indicating the quantiles
at which the input variables will be hold constant.</p>
<p>OR</p>
<p>A single value indicating the number of groups.
<a href="https://www.rdocumentation.org/link%20/kmeans?package=NeuralNetTools&amp;version=1.5.2&amp;to=stats"><strong><code>kmeans</code></strong></a>
clustering is used if this value is greater than 1.</p>
</td>
</tr>
<tr class="even">
<td>group_show</td>
<td>if set true, a barplot showing values of input
variables is returned instead.</td>
</tr>
</tbody>
</table></div>
<div class="sourceCode" id="cb637"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/lekprofile.html">lekprofile</a></span><span class="op">(</span><span class="va">mod3</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-10-1.png" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb638"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/lekprofile.html">lekprofile</a></span><span class="op">(</span><span class="va">mod3</span>, group_show <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-10-2.png" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb639"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/lekprofile.html">lekprofile</a></span><span class="op">(</span><span class="va">mod3</span>, group_vals <span class="op">=</span> <span class="fl">6</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-10-3.png" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb640"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/NeuralNetTools/man/lekprofile.html">lekprofile</a></span><span class="op">(</span><span class="va">mod3</span>, group_vals <span class="op">=</span> <span class="fl">6</span>, group_show <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="neuralnet_r_tutorial_files/figure-html/unnamed-chunk-10-4.png" width="672" style="display: block; margin: auto;"></div>
<p>These plots show the influence of varying each input variable at
different quantiles to the value of response outputs, while holding
other input variables constant. In the plots of lines, the x-axis
represents the values of each input variables, y-axis the values of the
response, and different lines different values of the input variables.
For example, the first plot shows that X1 and X3 are more sensitive than
X2 since changes in their values result in more different response
values respectively. The last plot shows that X1 is more sensitive since
its value changes more dramatically across groups.</p>
</div>
</div>
</div>
<div id="miscellaneous" class="section level2">
<h2>
<span class="header-section-number">48.3</span> Miscellaneous<a class="anchor" aria-label="anchor" href="#miscellaneous"><i class="fas fa-link"></i></a>
</h2>
<div id="other-useful-functions-from-the-package" class="section level4">
<h4>
<span class="header-section-number">48.3.0.1</span> Other useful functions from the package:<a class="anchor" aria-label="anchor" href="#other-useful-functions-from-the-package"><i class="fas fa-link"></i></a>
</h4>
<ol style="list-style-type: decimal">
<li>
<p>“neuralweights”: to retrieve model weights</p>
<ul>
<li>
<p>Return a two-element summary list of the network’s structure</p>
<ol style="list-style-type: decimal">
<li><p>a vector of number of nodes of each layer</p></li>
<li><p>a named list of model weights</p></li>
</ol>
</li>
<li><p>It is used implicitly in main functions. We can use it
explicitly when a numerical summary of the model weights is
needed.</p></li>
</ul>
</li>
<li>
<p>“pred_sens”: to retrieve predicted values for Lek Profile method</p>
<ul>
<li><p>Return a list of predictions whose each element corresponds to a
group in Lek Profile method.</p></li>
<li><p>It is used implicitly in “lefprofile”</p></li>
</ul>
</li>
</ol>
</div>
<div id="load-popular-datasets-for-neural-networks-from-rs-keras-package" class="section level4">
<h4>
<span class="header-section-number">48.3.0.2</span> Load popular datasets for neural networks from R’s keras package:<a class="anchor" aria-label="anchor" href="#load-popular-datasets-for-neural-networks-from-rs-keras-package"><i class="fas fa-link"></i></a>
</h4>
<p><a href="https://rdrr.io/cran/keras/f/vignettes/index.Rmd" class="uri">https://rdrr.io/cran/keras/f/vignettes/index.Rmd</a></p>
</div>
</div>
<div id="reference-3" class="section level2">
<h2>
<span class="header-section-number">48.4</span> Reference:<a class="anchor" aria-label="anchor" href="#reference-3"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: decimal">
<li><p><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6262849/" class="uri">&lt;https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6262849/&gt;</a></p></li>
<li><p><a href="https://cran.r-project.org/web/packages/NeuralNetTools/NeuralNetTools.pdf" class="uri">https://cran.r-project.org/web/packages/NeuralNetTools/NeuralNetTools.pdf</a></p></li>
<li><p><a href="https://cran.r-project.org/web/packages/nnet/nnet.pdf" class="uri">https://cran.r-project.org/web/packages/nnet/nnet.pdf</a></p></li>
<li><p><a href="https://cran.r-project.org/web/packages/RSNNS/RSNNS.pdf" class="uri">https://cran.r-project.org/web/packages/RSNNS/RSNNS.pdf</a></p></li>
<li><p><a href="https://www.ra.cs.uni-tuebingen.de/SNNS/UserManual/node308.html" class="uri">https://www.ra.cs.uni-tuebingen.de/SNNS/UserManual/node308.html</a></p></li>
<li><p><a href="https://www.rdocumentation.org/packages/RSNNS/versions/0.4-14/topics/mlp" class="uri">https://www.rdocumentation.org/packages/RSNNS/versions/0.4-14/topics/mlp</a></p></li>
</ol>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="tutorial-for-gg_cleveland.html"><span class="header-section-number">47</span> Tutorial for gg_cleveland</a></div>
<div class="next"><a href="r-dplyr-vs-python-pandas.html"><span class="header-section-number">49</span> R Dplyr vs Python Pandas</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#neural-network-tools-in-r"><span class="header-section-number">48</span> Neural network tools in R</a></li>
<li>
<a class="nav-link" href="#introduction-9"><span class="header-section-number">48.1</span> Introduction</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#packages-will-be-introduced"><span class="header-section-number">48.1.1</span> Packages will be introduced:</a></li>
<li><a class="nav-link" href="#some-background-knowledge-of-neural-networks"><span class="header-section-number">48.1.2</span> Some background knowledge of neural networks:</a></li>
<li><a class="nav-link" href="#data-pre-processing"><span class="header-section-number">48.1.3</span> Data pre-processing</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#visualization-of-neural-networks"><span class="header-section-number">48.2</span> Visualization of Neural Networks</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#neuralnettools-package"><span class="header-section-number">48.2.1</span> Neuralnettools package</a></li>
<li><a class="nav-link" href="#four-core-functions-of-neuralnettools"><span class="header-section-number">48.2.2</span> Four core functions of NeuralNetTools</a></li>
<li><a class="nav-link" href="#neural-interpretation-diagram-nid"><span class="header-section-number">48.2.3</span> Neural Interpretation Diagram (NID)</a></li>
<li><a class="nav-link" href="#neuralnettoolsplotnet"><span class="header-section-number">48.2.4</span> NeuralNetTools::plotnet</a></li>
<li><a class="nav-link" href="#alternative-to-nid"><span class="header-section-number">48.2.5</span> Alternative to NID:</a></li>
<li><a class="nav-link" href="#sensitivity-analysis"><span class="header-section-number">48.2.6</span> Sensitivity analysis:</a></li>
</ul>
</li>
<li><a class="nav-link" href="#miscellaneous"><span class="header-section-number">48.3</span> Miscellaneous</a></li>
<li><a class="nav-link" href="#reference-3"><span class="header-section-number">48.4</span> Reference:</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/jtr13/cc21fall2/blob/main/neuralnet_r_tutorial.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/jtr13/cc21fall2/edit/main/neuralnet_r_tutorial.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>EDAV Fall 2021 Tues/Thurs Community Contributions</strong>" was written by . It was last built on 2021-11-10.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
