<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 87 Urca: Unit Root Test and Cointegration Test | EDAV Fall 2021 Tues/Thurs Community Contributions</title>
<meta name="description" content="Zonghan Yue(zy2493), Alvin Pan (qp2134) library(urca) library(ggplot2) library(RCurl)  87.1 Introduction: Rstudio package urca developed by Bernhard Pfaff, Eric Zivot, Matthieu Stigler in 2016....">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 87 Urca: Unit Root Test and Cointegration Test | EDAV Fall 2021 Tues/Thurs Community Contributions">
<meta property="og:type" content="book">
<meta property="og:description" content="Zonghan Yue(zy2493), Alvin Pan (qp2134) library(urca) library(ggplot2) library(RCurl)  87.1 Introduction: Rstudio package urca developed by Bernhard Pfaff, Eric Zivot, Matthieu Stigler in 2016....">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 87 Urca: Unit Root Test and Cointegration Test | EDAV Fall 2021 Tues/Thurs Community Contributions">
<meta name="twitter:description" content="Zonghan Yue(zy2493), Alvin Pan (qp2134) library(urca) library(ggplot2) library(RCurl)  87.1 Introduction: Rstudio package urca developed by Bernhard Pfaff, Eric Zivot, Matthieu Stigler in 2016....">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script><script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script><script src="libs/plotly-binding-4.10.0/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script><link href="libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-2.5.1/plotly-latest.min.js"></script><script src="libs/d3-4.5.0/d3.min.js"></script><script src="libs/forceNetwork-binding-0.4/forceNetwork.js"></script><script src="libs/sankey-1/sankey.js"></script><script src="libs/sankeyNetwork-binding-0.4/sankeyNetwork.js"></script><link href="libs/vis-9.1.0/vis-network.min.css" rel="stylesheet">
<script src="libs/vis-9.1.0/vis-network.min.js"></script><script src="libs/visNetwork-binding-2.1.0/visNetwork.js"></script><link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet">
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script><script src="libs/dygraphs-1.1.1/shapes.js"></script><script src="libs/moment-2.8.4/moment.js"></script><script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script><script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script><script src="libs/dygraphs-binding-1.1.1.6/dygraphs.js"></script><script src="libs/proj4js-2.3.15/proj4.js"></script><link href="libs/highcharts-8.1.2/css/motion.css" rel="stylesheet">
<script src="libs/highcharts-8.1.2/highcharts.js"></script><script src="libs/highcharts-8.1.2/highcharts-3d.js"></script><script src="libs/highcharts-8.1.2/highcharts-more.js"></script><script src="libs/highcharts-8.1.2/modules/stock.js"></script><script src="libs/highcharts-8.1.2/modules/map.js"></script><script src="libs/highcharts-8.1.2/modules/annotations.js"></script><script src="libs/highcharts-8.1.2/modules/data.js"></script><script src="libs/highcharts-8.1.2/modules/drilldown.js"></script><script src="libs/highcharts-8.1.2/modules/item-series.js"></script><script src="libs/highcharts-8.1.2/modules/offline-exporting.js"></script><script src="libs/highcharts-8.1.2/modules/overlapping-datalabels.js"></script><script src="libs/highcharts-8.1.2/modules/exporting.js"></script><script src="libs/highcharts-8.1.2/modules/export-data.js"></script><script src="libs/highcharts-8.1.2/modules/funnel.js"></script><script src="libs/highcharts-8.1.2/modules/heatmap.js"></script><script src="libs/highcharts-8.1.2/modules/treemap.js"></script><script src="libs/highcharts-8.1.2/modules/sankey.js"></script><script src="libs/highcharts-8.1.2/modules/dependency-wheel.js"></script><script src="libs/highcharts-8.1.2/modules/organization.js"></script><script src="libs/highcharts-8.1.2/modules/solid-gauge.js"></script><script src="libs/highcharts-8.1.2/modules/streamgraph.js"></script><script src="libs/highcharts-8.1.2/modules/sunburst.js"></script><script src="libs/highcharts-8.1.2/modules/vector.js"></script><script src="libs/highcharts-8.1.2/modules/wordcloud.js"></script><script src="libs/highcharts-8.1.2/modules/xrange.js"></script><script src="libs/highcharts-8.1.2/modules/tilemap.js"></script><script src="libs/highcharts-8.1.2/modules/venn.js"></script><script src="libs/highcharts-8.1.2/modules/gantt.js"></script><script src="libs/highcharts-8.1.2/modules/timeline.js"></script><script src="libs/highcharts-8.1.2/modules/parallel-coordinates.js"></script><script src="libs/highcharts-8.1.2/modules/bullet.js"></script><script src="libs/highcharts-8.1.2/modules/coloraxis.js"></script><script src="libs/highcharts-8.1.2/modules/dumbbell.js"></script><script src="libs/highcharts-8.1.2/modules/lollipop.js"></script><script src="libs/highcharts-8.1.2/modules/series-label.js"></script><script src="libs/highcharts-8.1.2/plugins/motion.js"></script><script src="libs/highcharts-8.1.2/custom/reset.js"></script><script src="libs/highcharts-8.1.2/modules/boost.js"></script><script src="libs/highchart-binding-0.8.2/highchart.js"></script><script src="libs/detect-resize-0.5.3/jquery.resize.js"></script><link href="libs/jquery-ui-1.11.4/jquery-ui.min.css" rel="stylesheet">
<script src="libs/jquery-ui-1.11.4/jquery-ui.min.js"></script><script src="libs/vega-1.4.3/vega.min.js"></script><script src="libs/lodash-2.2.1/lodash.min.js"></script><script>var lodash = _.noConflict();</script><link href="libs/ggvis-0.4.7/css/ggvis.css" rel="stylesheet">
<script src="libs/ggvis-0.4.7/js/ggvis.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS -->
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">EDAV Fall 2021 Tues/Thurs Community Contributions</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Welcome!</a></li>
<li><a class="" href="community-contribution.html"><span class="header-section-number">2</span> Community Contribution</a></li>
<li><a class="" href="github-submission-instructions.html"><span class="header-section-number">3</span> GitHub submission instructions</a></li>
<li><a class="" href="sample-project.html"><span class="header-section-number">4</span> Sample project</a></li>
<li class="book-part">Cheatsheets</li>
<li><a class="" href="statistics-in-r-vs-python.html"><span class="header-section-number">5</span> Statistics in R vs Python</a></li>
<li><a class="" href="data-visualization-with-seaborn.html"><span class="header-section-number">6</span> Data Visualization with Seaborn</a></li>
<li><a class="" href="how-to-make-your-own-r-package.html"><span class="header-section-number">7</span> How to Make Your Own R package</a></li>
<li><a class="" href="rchess-package-cheatsheet.html"><span class="header-section-number">8</span> RChess package cheatsheet</a></li>
<li><a class="" href="hypothesis-testing-cheatsheet.html"><span class="header-section-number">9</span> Hypothesis testing cheatsheet</a></li>
<li><a class="" href="interactive-web-visualizations-for-r-cheatsheet.html"><span class="header-section-number">10</span> Interactive web visualizations for R cheatsheet"</a></li>
<li><a class="" href="ggforce.html"><span class="header-section-number">11</span> ggforce</a></li>
<li><a class="" href="gganimate-cheatsheet.html"><span class="header-section-number">12</span> GGanimate cheatsheet</a></li>
<li><a class="" href="statistical-tests-and-parameter-estimations-in-r-cheatsheet.html"><span class="header-section-number">13</span> Statistical Tests and Parameter Estimations in R Cheatsheet</a></li>
<li><a class="" href="ggalluvial-cheat-sheet.html"><span class="header-section-number">14</span> ggalluvial-cheat-sheet</a></li>
<li><a class="" href="introduction-to-plotly.html"><span class="header-section-number">15</span> Introduction to plotly</a></li>
<li><a class="" href="draw-graphs-using-python-and-r.html"><span class="header-section-number">16</span> draw graphs using python and R</a></li>
<li><a class="" href="data-visualization-packages-in-r.html"><span class="header-section-number">17</span> Data Visualization Packages in R</a></li>
<li><a class="" href="esquisse-cheat-sheet.html"><span class="header-section-number">18</span> Esquisse Cheat sheet</a></li>
<li><a class="" href="review-sheet-for-r-code-and-data-transformation.html"><span class="header-section-number">19</span> review sheet for r code and data transformation</a></li>
<li><a class="" href="scrape-twitter-data-using-r.html"><span class="header-section-number">20</span> Scrape Twitter data using R</a></li>
<li><a class="" href="r-note-and-mathematics-in-rmd-cheatsheet.html"><span class="header-section-number">21</span> R note and Mathematics in Rmd cheatsheet</a></li>
<li><a class="" href="textbook-notes.html"><span class="header-section-number">22</span> Textbook Notes</a></li>
<li><a class="" href="ggplot2-cheatsheet.html"><span class="header-section-number">23</span> ggplot2 cheatsheet</a></li>
<li><a class="" href="rstudio-cheatsheet.html"><span class="header-section-number">24</span> RStudio Cheatsheet</a></li>
<li><a class="" href="d3-visualization-in-r-cheatsheet.html"><span class="header-section-number">25</span> D3 Visualization in R Cheatsheet</a></li>
<li><a class="" href="colors.html"><span class="header-section-number">26</span> Colors</a></li>
<li><a class="" href="r-data-sets.html"><span class="header-section-number">27</span> R data sets</a></li>
<li><a class="" href="introduction-to-plotly-1.html"><span class="header-section-number">28</span> “Introduction to Plotly”</a></li>
<li><a class="" href="tidyverse-cheatsheet.html"><span class="header-section-number">29</span> Tidyverse Cheatsheet</a></li>
<li><a class="" href="learning-sql-with-its-r-dplyr-translation.html"><span class="header-section-number">30</span> Learning SQL with Its R dplyr Translation</a></li>
<li><a class="" href="animate-time-series-the-goyav-package.html"><span class="header-section-number">31</span> Animate Time Series : the goyav package</a></li>
<li><a class="" href="string-manipulation-in-r.html"><span class="header-section-number">32</span> String Manipulation in R</a></li>
<li><a class="" href="ggalluvial-cheatsheet.html"><span class="header-section-number">33</span> ggalluvial Cheatsheet</a></li>
<li class="book-part">Tutorials</li>
<li><a class="" href="tutorial-on-cluster-analysis.html"><span class="header-section-number">34</span> Tutorial on Cluster Analysis</a></li>
<li><a class="" href="how-to-integrate-r-with-postgresql.html"><span class="header-section-number">35</span> How to Integrate R with PostgreSQL</a></li>
<li><a class="" href="apply-function-in-r.html"><span class="header-section-number">36</span> Apply function in r</a></li>
<li><a class="" href="introduction-to-interactive-graphs-in-r.html"><span class="header-section-number">37</span> Introduction to interactive graphs in R</a></li>
<li><a class="" href="plot-and-analyze-stock-data-with-r.html"><span class="header-section-number">38</span> Plot and Analyze Stock Data with R</a></li>
<li><a class="" href="data-visulization-ordering.html"><span class="header-section-number">39</span> Data Visulization Ordering</a></li>
<li><a class="" href="tutorial-on-lattice-package-in-r.html"><span class="header-section-number">40</span> Tutorial on lattice package in R</a></li>
<li><a class="" href="network-visualization-in-r.html"><span class="header-section-number">41</span> Network Visualization in R</a></li>
<li><a class="" href="dplyr-tutorial-in-r.html"><span class="header-section-number">42</span> Dplyr tutorial in R</a></li>
<li><a class="" href="downloading-files.html"><span class="header-section-number">43</span> Downloading files</a></li>
<li><a class="" href="video-introduction-to-maps-with-ggmap.html"><span class="header-section-number">44</span> Video introduction to maps with ggmap</a></li>
<li><a class="" href="comparison-among-base-r-tidyverse-and-datatable.html"><span class="header-section-number">45</span> Comparison among base R, tidyverse, and datatable</a></li>
<li><a class="" href="raincloud-plot-101-density-plot-or-boxplotwhy-not-do-both.html"><span class="header-section-number">46</span> Raincloud plot 101: density plot or boxplot？Why not do both!</a></li>
<li><a class="" href="an-introduction-to-dygraph-in-r.html"><span class="header-section-number">47</span> An Introduction to Dygraph in R</a></li>
<li><a class="" href="streamlit-tutorial.html"><span class="header-section-number">48</span> Streamlit Tutorial</a></li>
<li><a class="" href="hive-plots-with-the-ggraph-and-hiver-packages.html"><span class="header-section-number">49</span> Hive plots with the ggraph and hiver packages</a></li>
<li><a class="" href="introduction-to-xai-explainable-ai-in-r.html"><span class="header-section-number">50</span> Introduction to XAI (Explainable AI) in R</a></li>
<li><a class="" href="tutorial-for-gg_cleveland.html"><span class="header-section-number">51</span> Tutorial for gg_cleveland</a></li>
<li><a class="" href="neural-network-tools-in-r.html"><span class="header-section-number">52</span> Neural network tools in R</a></li>
<li><a class="" href="r-dplyr-vs-python-pandas.html"><span class="header-section-number">53</span> R Dplyr vs Python Pandas</a></li>
<li><a class="" href="readable-plots.html"><span class="header-section-number">54</span> Readable Plots</a></li>
<li><a class="" href="introduction-to-exploratory-spatial-data-analysis-and-visualization-using-qgis.html"><span class="header-section-number">55</span> Introduction to exploratory spatial data analysis and visualization using QGIS</a></li>
<li><a class="" href="data-visualization-in-python-vs-r.html"><span class="header-section-number">56</span> Data Visualization in Python vs R</a></li>
<li><a class="" href="base-r-tutorial.html"><span class="header-section-number">57</span> Base R Tutorial</a></li>
<li><a class="" href="python-altair-visualization-method-tutorial.html"><span class="header-section-number">58</span> Python Altair Visualization Method Tutorial</a></li>
<li><a class="" href="r-to-python-easy-plot.html"><span class="header-section-number">59</span> R to python easy plot</a></li>
<li><a class="" href="introduction-to-models-and-prediction-evaluation.html"><span class="header-section-number">60</span> Introduction to models and prediction evaluation</a></li>
<li><a class="" href="introduction-to-interactive-time-series-visualizations-with-dygraphs-in-r.html"><span class="header-section-number">61</span> Introduction to Interactive Time Series Visualizations with dygraphs in R</a></li>
<li><a class="" href="integrate-r-with-python.html"><span class="header-section-number">62</span> Integrate R with Python</a></li>
<li><a class="" href="python-visualization-tutorial.html"><span class="header-section-number">63</span> Python Visualization Tutorial</a></li>
<li><a class="" href="gganimate-tutorial.html"><span class="header-section-number">64</span> Gganimate Tutorial</a></li>
<li><a class="" href="get-nba-dataset-in-r.html"><span class="header-section-number">65</span> Get NBA dataset in R</a></li>
<li><a class="" href="mtemplates.html"><span class="header-section-number">66</span> Mtemplates</a></li>
<li><a class="" href="introduction-to-time-series-analysis-in-r.html"><span class="header-section-number">67</span> Introduction to Time Series Analysis in R</a></li>
<li><a class="" href="storytelling-with-data.html"><span class="header-section-number">68</span> Storytelling with Data</a></li>
<li><a class="" href="tutorial-on-r-torch-package.html"><span class="header-section-number">69</span> Tutorial on R torch package</a></li>
<li><a class="" href="edav-tutorials-correlogram-calendar-heatmap-and-slopegram.html"><span class="header-section-number">70</span> EDAV Tutorials: Correlogram, Calendar Heatmap and Slopegram</a></li>
<li><a class="" href="recursive-codes-and-self-organized-map-with-r.html"><span class="header-section-number">71</span> Recursive codes and self-organized map with R</a></li>
<li><a class="" href="tutorial-of-three-ggplot2-based-packages.html"><span class="header-section-number">72</span> Tutorial of three ggplot2 based packages</a></li>
<li><a class="" href="a-step-by-step-tutorial-for-natural-language-processing-in-r.html"><span class="header-section-number">73</span> A Step by Step Tutorial for Natural Language Processing in R</a></li>
<li><a class="" href="tutorial-for-ggvis-and-its-comparison-with-ggplot2.html"><span class="header-section-number">74</span> Tutorial for ggvis and its Comparison with ggplot2</a></li>
<li><a class="" href="feature-selection-in-r.html"><span class="header-section-number">75</span> Feature selection in r</a></li>
<li><a class="" href="debugging-in-rstudio.html"><span class="header-section-number">76</span> Debugging in Rstudio</a></li>
<li><a class="" href="r-tutorial-cheatsheet.html"><span class="header-section-number">77</span> R tutorial cheatsheet</a></li>
<li><a class="" href="brief-introduction-of-ggpubr.html"><span class="header-section-number">78</span> Brief Introduction of ggpubr</a></li>
<li><a class="" href="r-based-data-organization-and-visualization.html"><span class="header-section-number">79</span> R based data organization and visualization</a></li>
<li><a class="" href="r-packages-for-map-visualization.html"><span class="header-section-number">80</span> R packages for map Visualization</a></li>
<li><a class="" href="common-git-command-lines-tutorial-when-working-on-studio.html"><span class="header-section-number">81</span> Common git command lines tutorial when working on studio</a></li>
<li><a class="" href="tutorial-of-radar-chart.html"><span class="header-section-number">82</span> Tutorial of radar chart</a></li>
<li><a class="" href="interactive-radar.html"><span class="header-section-number">83</span> Interactive Radar</a></li>
<li><a class="" href="r-shiny-tutorial.html"><span class="header-section-number">84</span> R shiny tutorial</a></li>
<li><a class="" href="tutorial-on-r-markdown.html"><span class="header-section-number">85</span> Tutorial on R Markdown</a></li>
<li><a class="" href="dlookr-package.html"><span class="header-section-number">86</span> Dlookr package</a></li>
<li><a class="active" href="urca-unit-root-test-and-cointegration-test.html"><span class="header-section-number">87</span> Urca: Unit Root Test and Cointegration Test</a></li>
<li><a class="" href="pygal-tutorial.html"><span class="header-section-number">88</span> pygal tutorial</a></li>
<li><a class="" href="comparing-excel-chart-making-with-rs.html"><span class="header-section-number">89</span> Comparing Excel Chart Making with R’s</a></li>
<li><a class="" href="joining-and-reshaping-in-r.html"><span class="header-section-number">90</span> Joining and reshaping in R</a></li>
<li><a class="" href="running-sql-queries-on-dataframes.html"><span class="header-section-number">91</span> Running Sql Queries on Dataframes</a></li>
<li><a class="" href="tidyverse.html"><span class="header-section-number">92</span> TidyVerse</a></li>
<li><a class="" href="how-to-animate-your-plots.html"><span class="header-section-number">93</span> How to animate your plots</a></li>
<li class="book-part">Project &amp; Workshops</li>
<li><a class="" href="introduction-to-analytics-consulting-at-accenture.html"><span class="header-section-number">94</span> Introduction to analytics consulting at Accenture</a></li>
<li><a class="" href="map-of-the-r-world.html"><span class="header-section-number">95</span> Map of the R world</a></li>
<li><a class="" href="alluvial-diagrams-and-their-implementation-using-ggalluvial-in-r.html"><span class="header-section-number">96</span> Alluvial diagrams and their implementation using GGalluvial in R</a></li>
<li><a class="" href="building-a-dashboard-in-r-for-data-analysis-and-visualization-using-shiny-package.html"><span class="header-section-number">97</span> Building a Dashboard in R for Data Analysis and Visualization using shiny package</a></li>
<li><a class="" href="rgl-package.html"><span class="header-section-number">98</span> RGL Package</a></li>
<li class="book-part">Data Visualization</li>
<li><a class="" href="an-introduction-to-pyecharts-package-in-python.html"><span class="header-section-number">99</span> An introduction to pyecharts package in Python</a></li>
<li><a class="" href="visualization-in-r-v.s.-python.html"><span class="header-section-number">100</span> Visualization in R v.s. Python</a></li>
<li><a class="" href="understand-data-with-plots.html"><span class="header-section-number">101</span> Understand data with plots</a></li>
<li><a class="" href="r-and-python-visualization.html"><span class="header-section-number">102</span> R and Python visualization</a></li>
<li><a class="" href="d-visualization-with-rgl-and-scatterplot3d.html"><span class="header-section-number">103</span> 3D Visualization with rgl and scatterplot3d</a></li>
<li><a class="" href="super-ggformat.html"><span class="header-section-number">104</span> Super ggformat</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="github-initial-setup.html"><span class="header-section-number">105</span> Github initial setup</a></li>
<li><a class="" href="tutorial-for-pull-request-mergers.html"><span class="header-section-number">106</span> Tutorial for pull request mergers</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/jtr13/cc21fall2">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="urca-unit-root-test-and-cointegration-test" class="section level1">
<h1>
<span class="header-section-number">87</span> Urca: Unit Root Test and Cointegration Test<a class="anchor" aria-label="anchor" href="#urca-unit-root-test-and-cointegration-test"><i class="fas fa-link"></i></a>
</h1>
<p>Zonghan Yue(zy2493), Alvin Pan (qp2134)</p>
<div class="sourceCode" id="cb1143"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">urca</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">RCurl</span><span class="op">)</span></code></pre></div>
<div id="introduction-20" class="section level2">
<h2>
<span class="header-section-number">87.1</span> Introduction:<a class="anchor" aria-label="anchor" href="#introduction-20"><i class="fas fa-link"></i></a>
</h2>
<p>Rstudio package urca developed by Bernhard Pfaff, Eric Zivot, Matthieu Stigler in 2016. “urca” is the abbreviation of the Unit Root and Cointegration Tests for Time Series Data. The package provides functions for users to do the cointegration and Unit Root test.</p>
<div id="dataset-description" class="section level4">
<h4>
<span class="header-section-number">87.1.0.1</span> Dataset Description:<a class="anchor" aria-label="anchor" href="#dataset-description"><i class="fas fa-link"></i></a>
</h4>
<p>Data Set scraped from OKEX exchange’s API. It is the minute level historical candlesticks of the ETH price.</p>
<p>Columns:
  time: the UTC time
  open: the first trade during that time period
  high: the highest price trade during that time period
  low: the lowest price trade during that time period
  close: the last trade during that time period
  volume: the quantity trades during that time period</p>
<p>Examples:</p>
<div class="sourceCode" id="cb1144"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">eth</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/connections.html">url</a></span><span class="op">(</span><span class="st">"https://raw.githubusercontent.com/yzh9810/edav_cc/main/eth-usdt.csv"</span><span class="op">)</span><span class="op">)</span>
<span class="va">eth</span><span class="op">$</span><span class="va">time</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/as.POSIXlt.html">as.POSIXlt</a></span><span class="op">(</span><span class="va">eth</span><span class="op">$</span><span class="va">time</span><span class="op">)</span></code></pre></div>
</div>
<div id="what-is-stationarity" class="section level4">
<h4>
<span class="header-section-number">87.1.0.2</span> What is stationarity ?<a class="anchor" aria-label="anchor" href="#what-is-stationarity"><i class="fas fa-link"></i></a>
</h4>
<p>A stationary time series is one whose properties do not depend on the time at which the series is observed. Thus, time series with trends, or with seasonality, are not stationary — the trend and seasonality will affect the value of the time series at different times. On the other hand, a white noise series is stationary — it does not matter when you observe it, it should look much the same at any point in time.</p>
<div class="sourceCode" id="cb1145"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/urca/man/plot-methods.html">plot</a></span><span class="op">(</span><span class="va">eth</span><span class="op">$</span><span class="va">time</span>, <span class="va">eth</span><span class="op">$</span><span class="va">close</span>, type<span class="op">=</span><span class="st">"l"</span>, xlab <span class="op">=</span> <span class="st">"Time"</span>, ylab <span class="op">=</span> <span class="st">"price"</span>, main <span class="op">=</span> <span class="st">"Unstationary: Eth Price"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="urca_unitroottest_cointegrationtest_files/figure-html/unnamed-chunk-4-1.png" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb1146"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">time</span> <span class="op">=</span> <span class="va">eth</span><span class="op">$</span><span class="va">time</span><span class="op">[</span><span class="fl">2</span><span class="op">:</span><span class="fl">100000</span><span class="op">]</span>
<span class="va">pre_close</span> <span class="op">=</span> <span class="va">eth</span><span class="op">$</span><span class="va">close</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">99999</span><span class="op">]</span>
<span class="va">next_close</span> <span class="op">=</span> <span class="va">eth</span><span class="op">$</span><span class="va">close</span><span class="op">[</span><span class="fl">2</span><span class="op">:</span><span class="fl">100000</span><span class="op">]</span>
<span class="va">close</span> <span class="op">=</span> <span class="va">next_close</span> <span class="op">-</span> <span class="va">pre_close</span>
<span class="fu"><a href="https://rdrr.io/pkg/urca/man/plot-methods.html">plot</a></span><span class="op">(</span><span class="va">time</span>, <span class="va">close</span>, type<span class="op">=</span><span class="st">"l"</span>, xlab <span class="op">=</span> <span class="st">"Time"</span>, ylab <span class="op">=</span> <span class="st">"price"</span>, main <span class="op">=</span> <span class="st">"stationary: Eth Return"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="urca_unitroottest_cointegrationtest_files/figure-html/unnamed-chunk-5-1.png" width="672" style="display: block; margin: auto;"></div>
</div>
<div id="what-is-unit-root" class="section level4">
<h4>
<span class="header-section-number">87.1.0.3</span> What is Unit Root?<a class="anchor" aria-label="anchor" href="#what-is-unit-root"><i class="fas fa-link"></i></a>
</h4>
<p>Unit Root: A unit root (also called a unit root process or a different stationary process) is a stochastic trend in a time series, sometimes called a “random walk with drift”; If a time series has a unit root, it shows a systematic pattern that is unpredictable.</p>
<p>A typical simplest time series model is autoregressive model,
<span class="math display">\[y_{t}=ay_{t-1}+\epsilon_{t}\]</span>
In this equation, the predict variable <span class="math inline">\(y_{t}\)</span> is only predicted by previous time period <span class="math inline">\(y_{t-1}\)</span> and the errors. The preceding model is a first-order autoregression model. If <span class="math inline">\(a &lt; 1\)</span>, the model is stationary. If <span class="math inline">\(a = 1\)</span>, the model is nonstationary, where <span class="math inline">\(a\)</span> is a stationary test.</p>
<p>Unit Root Tests:
Unit root tests are tests for stationarity in a time series. The shape of stationarity is if a shift in time doesn’t cause a change in the shape of the distribution. Unit roots are one cause for non-stationarity.</p>
</div>
<div id="what-is-cointegration-test" class="section level4">
<h4>
<span class="header-section-number">87.1.0.4</span> What is Cointegration test?<a class="anchor" aria-label="anchor" href="#what-is-cointegration-test"><i class="fas fa-link"></i></a>
</h4>
<p>Cointegration test is used to establish if there is a correlation between several time series in the long term.</p>
</div>
<div id="below-we-have-included-decumentations-and-experiments-of-several-popular-test-methods" class="section level4">
<h4>
<span class="header-section-number">87.1.0.5</span> Below we have included decumentations and experiments of several popular test methods<a class="anchor" aria-label="anchor" href="#below-we-have-included-decumentations-and-experiments-of-several-popular-test-methods"><i class="fas fa-link"></i></a>
</h4>
</div>
</div>
<div id="unit-root-tests-methods" class="section level2">
<h2>
<span class="header-section-number">87.2</span> Unit Root Tests methods:<a class="anchor" aria-label="anchor" href="#unit-root-tests-methods"><i class="fas fa-link"></i></a>
</h2>
<div id="the-dickey-fuller-test" class="section level4">
<h4>
<span class="header-section-number">87.2.0.1</span> The Dickey Fuller Test:<a class="anchor" aria-label="anchor" href="#the-dickey-fuller-test"><i class="fas fa-link"></i></a>
</h4>
<p>The Dickey Fuller Test is based on linear regression.</p>
<p>H0: null hypothes is that a unit root is present in an autoregressive time series model.</p>
<p>H1: a unit root is not present in an autoregressive time series model.</p>
<p>The formula for the test is AR(1) with <span class="math inline">\(\alpha = 0\)</span> and <span class="math inline">\(\beta = 0\)</span></p>
<p><span class="math display">\[y_{t} = (\sigma y_{t-1}) + \epsilon_{t}\]</span>
thus,
<span class="math display">\[\Delta y_{t} = (\sigma-1) y_{t-1} + \epsilon_{t} = \gamma y_{t-1} + \epsilon_{t}\]</span></p>
<p><strong>urca method: </strong></p>
<p>ur.df: Augmented-Dickey-Fuller Unit Root Test</p>
<p><strong>Arguments:</strong></p>
<p>  y:  Vector to be tested for a unit root.</p>
<p>  type:  Test type, either “none”, “drift” or “trend”.</p>
<p>For the AR(1) model:
<span class="math display">\[y_{t} = \alpha + \beta t +  \sigma y_{t-1} + \epsilon_{t}\]</span>
“none” means <span class="math inline">\(\alpha = 0\)</span> and <span class="math inline">\(\beta = 0\)</span>,</p>
<p>“drift” means <span class="math inline">\(\beta = 0\)</span>, and <span class="math inline">\(\alpha\)</span> not equal to 0</p>
<p>“trend” means both <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> are not equal to 0</p>
<p>  lags:  Number of lags for endogenous variables to be included.</p>
<p>Lags in time series is how many previous time period you used to predict target variable. For example, lags n means the equation you use is <span class="math display">\[y_{t} = \alpha + \beta t +  (\sigma_{t-1} y_{t-1} + \sigma_{t-2} y_{t-2} + \sigma_{t-3} y_{t-3} +...+ \sigma_{t-n} y_{t-n}) + \epsilon_{t}\]</span></p>
<p>  selectlags:  Lag selection can be achieved according to the Akaike AIC" or the Bayes “BIC” information criteria. The maximum number of lags considered is set by lags. The default is to use a “fixed” lag length set by lags.</p>
<p><strong>Usage</strong></p>
<p>  ur.df(y, type = c(“none”, “drift”, “trend”), lags = 1, selectlags = c(“Fixed”, “AIC”, “BIC”))</p>
<p><strong>Example</strong></p>
<div class="sourceCode" id="cb1147"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">urtest</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/urca/man/ur.df.html">ur.df</a></span><span class="op">(</span><span class="va">eth</span><span class="op">$</span><span class="va">close</span>, type<span class="op">=</span><span class="st">"none"</span>, lags <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/urca/man/summary-methods.html">summary</a></span><span class="op">(</span><span class="va">urtest</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression none 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 - 1 + z.diff.lag)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -175.109   -2.053   -0.014    2.026  129.091 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## z.lag.1    7.198e-07  3.212e-06   0.224    0.823    
## z.diff.lag 1.897e-02  1.985e-03   9.553   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.832 on 253595 degrees of freedom
## Multiple R-squared:  0.00036,    Adjusted R-squared:  0.0003521 
## F-statistic: 45.66 on 2 and 253595 DF,  p-value: &lt; 2.2e-16
## 
## 
## Value of test-statistic is: 0.2241 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau1 -2.58 -1.95 -1.62</code></pre>
<p><strong>Interpretation</strong></p>
<p>Value of test-statistic is 0.2241 and the Critical values for test statistics are: tau1 -2.58 -1.95 -1.62 for (1%, 5%, 10%). Thus, We reject the null, which means a unit root is present. The “z.lag1” is the <span class="math inline">\(\gamma\)</span> term, the coefficient for the lag term (y(t-1)), which is p=0.823, implies that gamma isn’t statistically significant to this model.</p>
<p>However, the R-square is only 0.00036, which means the time series is not satisfied the non-draft and non-trend model. Thus, the model is not actualy fit the data.</p>
</div>
<div id="the-elliottrothenbergstock-test" class="section level4">
<h4>
<span class="header-section-number">87.2.0.2</span> The Elliott–Rothenberg–Stock Test:<a class="anchor" aria-label="anchor" href="#the-elliottrothenbergstock-test"><i class="fas fa-link"></i></a>
</h4>
<p>The Elliott–Rothenberg–Stock Test have two subtest: P-test takes the error term’s serial correlation into account, the DF-GLS test can be applied to detrended data without intercept.</p>
<p>H0: null hypothes is that a unit root is present in an autoregressive time series model.</p>
<p>H1: a unit root is not present in an autoregressive time series model.</p>
<p><strong>urca method: </strong></p>
<p>ur.ers: Elliott, Rothenberg &amp; Stock Unit Root Test</p>
<p><strong>Arguments:</strong></p>
<p>  y:  Vector to be tested for a unit root.</p>
<p>  type:  Test type, either “DF-GLS” (default), or “P-test”.</p>
<p>What Is P-test?</p>
<p>The p-value approach to hypothesis testing uses the calculated probability to determine whether there is evidence to reject the null hypothesis.</p>
<p>What Is DF-GLS?</p>
<p>ADF-GLS test (or DF-GLS test) is a test for a unit root in an economic time series sample. It locally de-trends (de-means) data series to efficiently estimate the deterministic parameters of the series, and use the transformed data to perform a usual ADF unit root test.</p>
<p>  model:  The deterministic model used for detrending.</p>
<p>A detrend involves removing the effects of trend from a data set to show only the differences in values from the trend; it allows cyclical and other patterns to be identified. Detrending can be done using regression analysis and other statistical techniques. Detrending shows a different aspect of time series data by removing deterministic and stochastic trends.</p>
<p>  lag.max:  The maximum numbers of lags used for testing of a decent lag truncation for the “P-test” (BIC used), or the maximum number of lagged differences to be included in the test regression for “DF-GLS”.</p>
<p><strong>Usage</strong></p>
<p>  ur.ers(y, type = c(“DF-GLS”, “P-test”), model = c(“constant”, “trend”), lag.max = 4)</p>
<p>We reject the null hypothesis if the test statistics is greater than 5% confidence value.</p>
<p><strong>Example</strong></p>
<div class="sourceCode" id="cb1149"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">urtest</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/urca/man/ur.ers.html">ur.ers</a></span><span class="op">(</span><span class="va">eth</span><span class="op">$</span><span class="va">close</span>, type<span class="op">=</span><span class="st">"P-test"</span>, model<span class="op">=</span><span class="st">"const"</span>, lag.max<span class="op">=</span><span class="fl">6</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/urca/man/summary-methods.html">summary</a></span><span class="op">(</span><span class="va">urtest</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Elliot, Rothenberg and Stock Unit Root Test # 
## ############################################### 
## 
## Test of type P-test 
## detrending of series with intercept 
## 
## Value of test-statistic is: 6.3283 
## 
## Critical values of P-test are:
##                 1pct 5pct 10pct
## critical values 1.99 3.26  4.48</code></pre>
<p><strong>Intepretation</strong></p>
<p>Test-statistic is: 6.3283, the Critical values of P-test is 1.99, 3.26, 4.48, which for 1%, 5%, 10%, we can not reject the null hypothes. It means that eth is nonstationary.</p>
</div>
<div id="the-schmidtphillips-test" class="section level4">
<h4>
<span class="header-section-number">87.2.0.3</span> The Schmidt–Phillips Test:<a class="anchor" aria-label="anchor" href="#the-schmidtphillips-test"><i class="fas fa-link"></i></a>
</h4>
<p>The Schmidt–Phillips Test includes the coefficients of the deterministic variables in the null and alternate hypotheses. Subtypes are the rho-test and the tau-test.</p>
<p>H0: null hypothes is that an observable time series is stationary around a deterministic trend.</p>
<p>H1: a deterministic trend time series have a unit root</p>
<p>A process Y is said to be trend-stationary if</p>
<p><span class="math display">\[Y(t) = f(t) + e_{t}\]</span>
f is any function from R to R. The <span class="math inline">\(e_{t}\)</span> is the stationary process.</p>
<p>The Adjusted R-squared: 0.9999 which means the eth time series fit the trend model.</p>
<p>The p-value for the y.lagged &lt; 0.01, we can reject the null hypothesis. It means that eth is an observable time series is nonstationary around a deterministic trend.</p>
<p><strong>urca method: </strong></p>
<p>ur.sp: The Schmidt–Phillips Test</p>
<p><strong>Arguments:</strong></p>
<p>  y:  Vector to be tested for a unit root.</p>
<p>  type:  Test type, either ‘tau’ or ‘rho’ test.</p>
<p>tau test:</p>
<p>Kendall’s Tau: usually smaller values than Spearman’s rho correlation. Calculations based on concordant and discordant pairs. Insensitive to error. P values are more accurate with smaller sample sizes</p>
<p>rho test:</p>
<p>Spearman’s rho usually have larger values than Kendall’s Tau. Calculations based on deviations. Much more sensitive to error and discrepancies in data.</p>
<p>  pol.deg:  Degree of polynomial in the test regression.</p>
<p>  signif:  Significance level for the critical value of the test statistic.</p>
<p><strong>Usage</strong></p>
<p>  ur.sp(y, type = c(“tau”, “rho”), pol.deg = c(1, 2, 3, 4),
signif = c(0.01, 0.05, 0.1))</p>
<p><strong>Example</strong></p>
<div class="sourceCode" id="cb1151"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">urtest</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/urca/man/ur.sp.html">ur.sp</a></span><span class="op">(</span><span class="va">eth</span><span class="op">$</span><span class="va">close</span>, type<span class="op">=</span><span class="st">"tau"</span>, pol.deg<span class="op">=</span><span class="fl">1</span>, signif<span class="op">=</span><span class="fl">0.05</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/urca/man/summary-methods.html">summary</a></span><span class="op">(</span><span class="va">urtest</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## ################################### 
## # Schmidt-Phillips Unit Root Test # 
## ################################### 
## 
## 
## Call:
## lm(formula = sp.data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -176.877   -2.054   -0.018    2.018  128.146 
## 
## Coefficients:
##              Estimate Std. Error   t value Pr(&gt;|t|)    
## (Intercept) 6.962e-02  4.456e-02     1.562    0.118    
## y.lagged    1.000e+00  1.640e-05 60984.887   &lt;2e-16 ***
## trend.exp1  2.150e-07  1.442e-07     1.491    0.136    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.833 on 253595 degrees of freedom
## Multiple R-squared:  0.9999, Adjusted R-squared:  0.9999 
## F-statistic: 2.25e+09 on 2 and 253595 DF,  p-value: &lt; 2.2e-16
## 
## 
## Value of test-statistic is: -1.562 
## Critical value for a significance level of 0.05 
## is: -3.02</code></pre>
<p><strong>Interpretation</strong>
From the t-test, test-statistic is: -1.562, Critical value for a significance level of 0.05 is: -3.02. Thus, we have to reject the null hypothesis.</p>
</div>
<div id="the-zivot-andrews-test" class="section level4">
<h4>
<span class="header-section-number">87.2.0.4</span> The Zivot-Andrews test:<a class="anchor" aria-label="anchor" href="#the-zivot-andrews-test"><i class="fas fa-link"></i></a>
</h4>
<p>The Zivot-Andrews test allows a break at an unknown point in the intercept or linear trend.</p>
<p>H0: a null hypothesis of a unit root process with drift that excludes exogenous structural change</p>
<p>H1: the time series is stationary that excludes exogenous structural change
<strong>urca method: </strong></p>
<p>ur.za: Zivot &amp; Andrews Unit Root Test</p>
<p><strong>Arguments:</strong></p>
<p>  y:  Vector to be tested for a unit root.</p>
<p>  model:  Specification if the potential break occured in either the intercept, the linear trend or in both.</p>
<p>  lag:  The highest number of lagged endogenous differenced variables to be included in the test regression.</p>
<p><strong>Usage</strong></p>
<p>  ur.za(y, model = c(“intercept”, “trend”, “both”), lag=NULL)</p>
<p><strong>Example</strong></p>
<div class="sourceCode" id="cb1153"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">urtest</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/urca/man/ur.za.html">ur.za</a></span><span class="op">(</span><span class="va">eth</span><span class="op">$</span><span class="va">close</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">1000</span><span class="op">]</span>, model<span class="op">=</span><span class="st">"intercept"</span>, lag<span class="op">=</span><span class="fl">2</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/urca/man/summary-methods.html">summary</a></span><span class="op">(</span><span class="va">urtest</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## ################################ 
## # Zivot-Andrews Unit Root Test # 
## ################################ 
## 
## 
## Call:
## lm(formula = testmat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -10.9326  -1.4341  -0.0814   1.4239  26.2689 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.114e+02  1.990e+01   5.598 2.80e-08 ***
## y.l1         9.597e-01  7.193e-03 133.431  &lt; 2e-16 ***
## trend        1.081e-03  4.467e-04   2.421   0.0156 *  
## y.dl1       -2.652e-02  3.124e-02  -0.849   0.3961    
## y.dl2       -1.065e-02  3.123e-02  -0.341   0.7331    
## du           2.970e+00  5.658e-01   5.250 1.86e-07 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.733 on 991 degrees of freedom
##   (3 observations deleted due to missingness)
## Multiple R-squared:  0.9918, Adjusted R-squared:  0.9918 
## F-statistic: 2.397e+04 on 5 and 991 DF,  p-value: &lt; 2.2e-16
## 
## 
## Teststatistic: -5.6 
## Critical values: 0.01= -5.34 0.05= -4.8 0.1= -4.58 
## 
## Potential break point at position: 116</code></pre>
<p>x, we have sufficient evidence to reject the null that the unit root has a unit root with a single break.</p>
<p>Intepretation:</p>
<p>The test said that Potential break point at 116 position. The break position is the place that the series got structural breaks.</p>
<p>Since both the p-values of the intercept and y.l1 are &lt; 0.05 and test-statistic -5.6 less than the Critical values of P-test is -4.8. We can can reject the null hypothes with 95 percentage confidence. It means that eth is stationary with drift before the break.</p>
</div>
<div id="the-johansen-procedure-test" class="section level4">
<h4>
<span class="header-section-number">87.2.0.5</span> The Johansen-Procedure test:<a class="anchor" aria-label="anchor" href="#the-johansen-procedure-test"><i class="fas fa-link"></i></a>
</h4>
<p>The Johansen-Procedure test is a procedure for testing cointegration of several time series.</p>
<p><strong>urca method: </strong></p>
<p>ca.jo: A Unit Root and Cointegration Test for Time Series Data</p>
<p><strong>Arguments:</strong></p>
<p>  x:  Data frame/matrix to be tested. Given a general VAR model, <span class="math display">\[X_t = \Pi_1 X_{t-1} + \dots + \Pi_k X_{t-k} + \mu + {\Phi D}_t + \varepsilon_t , \quad (t = 1, \dots, T),\]</span></p>
<p>  type:  The type of test to be conducted, either “eigen”(eigenvalue) or “trace”.</p>
<p>  ecdet:  Character, ‘none’ for no intercept in cointegration, ‘const’ for constant term in cointegration and ‘trend’ for trend variable in cointegration.</p>
<p>  K:  The lag order of the series (levels) in the Vector autoregression(VAR).</p>
<p>  spec:  Determines the specification of the vector error correction model(VECM).</p>
<p>   If spec=“longrun”, the VECM is estimated by:
<span class="math display">\[\Delta X_t = \Gamma_1 \Delta X_{t-1} + \dots + \Gamma_{p-1} \Delta X_{t-p+1} + {\Pi X}_{t-p} + \mu + {\Phi D}_t + \varepsilon_t, \quad (t = 1, \dots , T),\]</span>
   where <span class="math display">\[\Gamma_i = \Pi_1 + \dots + \Pi_i - I, \quad (i = 1, \dots , p-1),\]</span>
<span class="math display">\[\Pi = \Pi_1 + \dots + \Pi_p - I\]</span></p>
<p>   The <span class="math inline">\(\Gamma_i\)</span> matrices contain the cumulative long-run impacts.</p>
<p>   Else spec=“transitory”, the VECM is estimated by:
<span class="math display">\[\Delta X_t = \Gamma_1 \Delta X_{t-1} + \dots + \Gamma_{p-1} \Delta X_{t-p+1} + {\Pi X}_{t-1} + \mu + {\Phi D}_t + \varepsilon_t\]</span>
   where <span class="math display">\[\Gamma_i = \Pi_{i+1} + \dots + \Pi_p - I, \quad(i = 1, \dots , p-1),\]</span></p>
<p><span class="math display">\[\Pi = \Pi_1 + \dots + \Pi_p - I.\]</span>
   The <span class="math inline">\(\Pi\)</span> matrix is the same as in the longrun VECM.</p>
<p>   Both inferences drawn on <span class="math inline">\(\Pi\)</span> and the explanatory power will be the same, but the <span class="math inline">\(\Gamma_i\)</span> matrices are no longer the same in terms of measuring transitory effects.</p>
<p>  season:  If seasonal dummies should be included, the data frequency must be set accordingly, i.e ‘4’ for quarterly data. If “season” is not NULL, centered seasonal dummy variables are included.</p>
<p>  dumvar:  If dummy variables should be included, a matrix with row dimension equal to x can be provided. If “dumvar” is not NULL, a matrix of dummy variables is included in the VECM. Furthermore, the number of rows of the matrix containing the dummy variables must be equal to the row number of x</p>
<p>Note: Critical values are only reported for systems with less than 11 variables and are taken from Osterwald-Lenum.</p>
<p><strong>Usage</strong></p>
<p>  ca.jo(x, type = c(“eigen”, “trace”), ecdet = c(“none”, “const”, “trend”), K = 2,
spec=c(“longrun”, “transitory”), season = NULL, dumvar = NULL)</p>
<p>  We denote <span class="math inline">\(r\)</span> as the rank of the matrix <span class="math inline">\(\Pi\)</span> and it’s upper bounded by the number of time series vectors under test(Denoted as <span class="math inline">\(n\)</span>), where <span class="math inline">\(r = 0\)</span> represents the test for presence of cointegration. It sequentially tests whether <span class="math inline">\(r \leq k\)</span>, where <span class="math inline">\(k \in [0, n-1]\)</span>. We normally reject a null hypothesis if the test statistics is larger than 5% confidence level estimate, where the best estimate of the rank represents the number time series that the linear combinations requires to form a stationary series. Then we can use the eigenvector that corresponds to the largest eigenvalue to compute the linear combinations w.r.t <span class="math inline">\(r\)</span>.</p>
<p><strong>Example</strong></p>
<p>We first extract the target time series stock vectors from the 2 datasets</p>
<div class="sourceCode" id="cb1155"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">xrp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/connections.html">url</a></span><span class="op">(</span><span class="st">"https://raw.githubusercontent.com/yzh9810/edav_cc/main/xrp-usdt.csv"</span><span class="op">)</span><span class="op">)</span>
<span class="va">eth</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/connections.html">url</a></span><span class="op">(</span><span class="st">"https://raw.githubusercontent.com/yzh9810/edav_cc/main/eth-usdt.csv"</span><span class="op">)</span><span class="op">)</span>
<span class="va">xrp</span><span class="op">$</span><span class="va">time</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/as.POSIXlt.html">as.POSIXlt</a></span><span class="op">(</span><span class="va">xrp</span><span class="op">$</span><span class="va">time</span><span class="op">)</span>
<span class="va">eth</span><span class="op">$</span><span class="va">time</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/as.POSIXlt.html">as.POSIXlt</a></span><span class="op">(</span><span class="va">eth</span><span class="op">$</span><span class="va">time</span><span class="op">)</span></code></pre></div>
<p>We first visualize the 2 time series data:</p>
<div class="sourceCode" id="cb1156"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/urca/man/plot-methods.html">plot</a></span><span class="op">(</span><span class="va">xrp</span><span class="op">$</span><span class="va">time</span>, <span class="va">xrp</span><span class="op">$</span><span class="va">close</span>, type<span class="op">=</span><span class="st">"l"</span>, xlab <span class="op">=</span> <span class="st">"Time"</span>, ylab <span class="op">=</span> <span class="st">"close"</span>, col<span class="op">=</span><span class="st">"red"</span>, main <span class="op">=</span> <span class="st">"Stock timeseries"</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">10</span><span class="op">)</span><span class="op">)</span>
<span class="co">#apply logorithm to eth data since the magnitudes are significantly higher.</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="va">eth</span><span class="op">$</span><span class="va">time</span>, <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">eth</span><span class="op">$</span><span class="va">close</span><span class="op">)</span>, col<span class="op">=</span><span class="st">"blue"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="urca_unitroottest_cointegrationtest_files/figure-html/unnamed-chunk-11-1.png" width="672" style="display: block; margin: auto;"></div>
<p>Now we do the modelling:</p>
<div class="sourceCode" id="cb1157"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">stock</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">xrp</span><span class="op">$</span><span class="va">close</span>, x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">eth</span><span class="op">$</span><span class="va">close</span><span class="op">)</span><span class="op">)</span>
<span class="va">coint</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/urca/man/ca.jo.html">ca.jo</a></span><span class="op">(</span><span class="va">stock</span>, type<span class="op">=</span><span class="st">"trace"</span>, ecdet<span class="op">=</span><span class="st">"trend"</span>, K<span class="op">=</span><span class="fl">2</span>, spec<span class="op">=</span><span class="st">"longrun"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/urca/man/summary-methods.html">summary</a></span><span class="op">(</span><span class="va">coint</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## ###################### 
## # Johansen-Procedure # 
## ###################### 
## 
## Test type: trace statistic , with linear trend in cointegration 
## 
## Eigenvalues (lambda):
## [1]  1.033152e-04  2.027439e-05 -6.352747e-21
## 
## Values of teststatistic and critical values of test:
## 
##           test 10pct  5pct  1pct
## r &lt;= 1 |  5.14 10.49 12.25 16.26
## r = 0  | 31.34 22.76 25.32 30.45
## 
## Eigenvectors, normalised to first column:
## (These are the cointegration relations)
## 
##                   y.l2          x.l2     trend.l2
## y.l2      1.000000e+00  1.000000e+00 1.000000e+00
## x.l2     -1.210520e+00 -8.299038e+00 1.805231e-01
## trend.l2  1.438052e-06  1.884477e-05 9.576652e-06
## 
## Weights W:
## (This is the loading matrix)
## 
##              y.l2         x.l2      trend.l2
## y.d -1.237713e-04 5.093904e-06 -1.371860e-20
## x.d  3.424685e-05 4.744542e-06 -1.730493e-21</code></pre>
<p><strong>Interpretation</strong></p>
<p>There are 3 generated eigenvalues and the largest one is 1.03e-4. In the next section, there are 2 hypotheses of <span class="math inline">\(r\leq 1\)</span> and <span class="math inline">\(r = 0\)</span>, where <span class="math inline">\(r\)</span> is the rank of the matrix <span class="math inline">\(\Pi\)</span> and it’s upper bounded by the number of time series vectors under test(In this case <span class="math inline">\(r \leq 2\)</span>). column 1,2,3,4 contain test statistics, 10%, 5% and 1% confidence level values respectively.</p>
<p>The test statistics 31.34 is greater 30.45, which is the 1% confidence level value. Hence we have sufficient evidence to reject the null hypothesis that there is no cointegration. But since for <span class="math inline">\(r \leq 1\)</span> the 10% confidence level value is 10.49, which is higher than the test statistics, we don’t have sufficient evidence to reject that <span class="math inline">\(r \leq 1\)</span>. Thus the test tells us we only need one of the two time series vectors to form a stationary series. The eigenvector that has the largest eigenvalue is column y.12 of the matrix in section 3, where we only need one of y.12 and x.12 to form a stationary series. We plot the 2 series weighted by their corresponding eigenvalues below.</p>
<div class="sourceCode" id="cb1159"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/urca/man/plot-methods.html">plot</a></span><span class="op">(</span><span class="va">xrp</span><span class="op">$</span><span class="va">time</span>, <span class="va">stock</span><span class="op">$</span><span class="va">y</span>, type<span class="op">=</span><span class="st">"l"</span>, col <span class="op">=</span> <span class="st">"red"</span>, xlab <span class="op">=</span> <span class="st">"Time"</span>, ylab <span class="op">=</span> <span class="st">"close"</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">10</span>,<span class="fl">2</span><span class="op">)</span>, main <span class="op">=</span> <span class="st">"Stationary series"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="va">xrp</span><span class="op">$</span><span class="va">time</span>, <span class="op">-</span><span class="fl">1.210520</span><span class="op">*</span><span class="va">stock</span><span class="op">$</span><span class="va">x</span>, col <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="urca_unitroottest_cointegrationtest_files/figure-html/unnamed-chunk-13-1.png" width="672" style="display: block; margin: auto;"></div>
<p>References:</p>
<p>Bernhard Pfaff. Package ‘urca’. September 6, 2016, from <a href="https://cran.r-project.org/web/packages/urca/urca.pdf" class="uri">https://cran.r-project.org/web/packages/urca/urca.pdf</a></p>
<p>ur.sp: Schmidt &amp; Phillips Unit Root Test.(2020) <a href="https://rdrr.io/cran/urca/" class="uri">https://rdrr.io/cran/urca/</a></p>
<p>YUGESH VERMA. Dickey-Fuller Test In Time-Series Analysis. Aug 18, 2021, from <a href="https://analyticsindiamag.com/complete-guide-to-dickey-fuller-test-in-time-series-analysis/" class="uri">https://analyticsindiamag.com/complete-guide-to-dickey-fuller-test-in-time-series-analysis/</a></p>
<p>aptech, A Guide to Conducting Cointegration Tests, JANUARY 28, 2020 <a href="https://www.aptech.com/blog/a-guide-to-conducting-cointegration-tests/" class="uri">https://www.aptech.com/blog/a-guide-to-conducting-cointegration-tests/</a></p>
<p>Peter Schmidt, Peter C.B. Phillips, Cowles Foundation for Research in Economics at Yale University October, 1989
<a href="https://cowles.yale.edu/sites/default/files/files/pub/d09/d0933.pdf" class="uri">https://cowles.yale.edu/sites/default/files/files/pub/d09/d0933.pdf</a></p>
<p>Schmidt, P. and Phillips, P.C.B. (1992), LM Test for a Unit Root in the Presence of Deterministic Trends, Oxford Bulletin of Economics and Statistics, 54(3), 257–287.</p>
<p>Zivot, E. and Andrews, Donald W.K. (1992), Further Evidence on the Great Crash, the Oil-Price Shock, and the Unit-Root Hypothesis, Journal of Business &amp; Economic Statistics, 10(3), 251–270.</p>
<p>Johansen test
<a href="https://en.wikipedia.org/wiki/Johansen_test" class="uri">https://en.wikipedia.org/wiki/Johansen_test</a></p>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="dlookr-package.html"><span class="header-section-number">86</span> Dlookr package</a></div>
<div class="next"><a href="pygal-tutorial.html"><span class="header-section-number">88</span> pygal tutorial</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#urca-unit-root-test-and-cointegration-test"><span class="header-section-number">87</span> Urca: Unit Root Test and Cointegration Test</a></li>
<li><a class="nav-link" href="#introduction-20"><span class="header-section-number">87.1</span> Introduction:</a></li>
<li><a class="nav-link" href="#unit-root-tests-methods"><span class="header-section-number">87.2</span> Unit Root Tests methods:</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/jtr13/cc21fall2/blob/main/urca_unitroottest_cointegrationtest.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/jtr13/cc21fall2/edit/main/urca_unitroottest_cointegrationtest.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>EDAV Fall 2021 Tues/Thurs Community Contributions</strong>" was written by . It was last built on 2021-11-13.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
